<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LombaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('m_lombas')->insert([
            [
                // 'keahlian_id' => 1,
                'tingkatan_id' => 2,
                'semester_id' => 7,
                'lomba_nama' => 'Lomba Frontend Web Design',
                'lomba_penyelenggara' => 'Dicoding',
                'lomba_kategori' => 'Web Design',
                'lomba_tanggal_mulai' => '2024-09-01',
                'lomba_tanggal_selesai' => '2024-09-05',
                'lomba_link_pendaftaran' => '',
                'lomba_link_poster' => '',
            ],
            [
                // 'keahlian_id' => 2,
                'tingkatan_id' => 3,
                'semester_id' => 8,
                'lomba_nama' => 'Backend API Development Contest',
                'lomba_penyelenggara' => 'PENS',
                'lomba_kategori' => 'Backend Programming',
                'lomba_tanggal_mulai' => '2025-04-10',
                'lomba_tanggal_selesai' => '2025-04-15',
                'lomba_link_pendaftaran' => '',
                'lomba_link_poster' => '',
            ],
            [
                // 'keahlian_id' => 3,
                'tingkatan_id' => 2,
                'semester_id' => 8,
                'lomba_nama' => 'Indie Game Development Jam',
                'lomba_penyelenggara' => 'GameDev Indonesia',
                'lomba_kategori' => 'Game Developer',
                'lomba_tanggal_mulai' => '2025-07-01',
                'lomba_tanggal_selesai' => '2025-07-10',
                'lomba_link_pendaftaran' => '',
                'lomba_link_poster' => '',
            ],
            [
                'tingkatan_id' => 1,
                'semester_id' => 7,
                'lomba_nama' => 'React Developer',
                'lomba_penyelenggara' => 'Kominfo',
                'lomba_kategori' => 'Web Design',
                'lomba_tanggal_mulai' => '2024-10-17',
                'lomba_tanggal_selesai' => '2024-10-22',
                'lomba_link_pendaftaran' => 'https://reyes.com/sint-et-libero-maxime-delectus.html',
                'lomba_link_poster' => 'https://placeimg.com/640/480',
            ],
            [
                'tingkatan_id' => 5,
                'semester_id' => 7,
                'lomba_nama' => 'Android Developer',
                'lomba_penyelenggara' => 'Telkom University',
                'lomba_kategori' => 'Data Science',
                'lomba_tanggal_mulai' => '2024-10-03',
                'lomba_tanggal_selesai' => '2024-10-13',
                'lomba_link_pendaftaran' => 'http://zemlak.com/autem-est-enim-aut-autem-non.html',
                'lomba_link_poster' => 'https://placeimg.com/640/480',
            ],
            [
                'tingkatan_id' => 1,
                'semester_id' => 7,
                'lomba_nama' => 'UI/UX Designer',
                'lomba_penyelenggara' => 'ITS Surabaya',
                'lomba_kategori' => 'Network',
                'lomba_tanggal_mulai' => '2024-11-28',
                'lomba_tanggal_selesai' => '2024-12-07',
                'lomba_link_pendaftaran' => 'https://jast.org/delectus-mollitia-at-et-voluptatem-ut-ut.html',
                'lomba_link_poster' => 'https://placeimg.com/640/480',
            ],
            [
                'tingkatan_id' => 4,
                'semester_id' => 7,
                'lomba_nama' => 'Graphic Designer',
                'lomba_penyelenggara' => 'Dicoding',
                'lomba_kategori' => 'Software Testing',
                'lomba_tanggal_mulai' => '2024-10-15',
                'lomba_tanggal_selesai' => '2024-10-18',
                'lomba_link_pendaftaran' => 'http://mraz.com/exercitationem-explicabo-deleniti-qui-nobis-ipsum.html',
                'lomba_link_poster' => 'https://placeimg.com/640/480',
            ],
            [
                'tingkatan_id' => 4,
                'semester_id' => 7,
                'lomba_nama' => 'Data Scientist',
                'lomba_penyelenggara' => 'Polinema',
                'lomba_kategori' => 'Web Design',
                'lomba_tanggal_mulai' => '2025-01-11',
                'lomba_tanggal_selesai' => '2025-01-16',
                'lomba_link_pendaftaran' => 'https://macejkovic.com/qui-voluptatibus-eum-iusto-sit-et-eum-est.html',
                'lomba_link_poster' => 'https://placeimg.com/640/480',
            ],
            [
                'tingkatan_id' => 5,
                'semester_id' => 7,
                'lomba_nama' => 'Java Developer',
                'lomba_penyelenggara' => 'Polinema',
                'lomba_kategori' => 'Backend Programming',
                'lomba_tanggal_mulai' => '2024-11-03',
                'lomba_tanggal_selesai' => '2024-11-13',
                'lomba_link_pendaftaran' => 'https://schmidt.com/exercitationem-reiciendis-molestiae.html',
                'lomba_link_poster' => 'https://placeimg.com/640/480',
            ],
            [
                'tingkatan_id' => 2,
                'semester_id' => 7,
                'lomba_nama' => 'Python Developer',
                'lomba_penyelenggara' => 'Microsoft Indonesia',
                'lomba_kategori' => 'UI/UX',
                'lomba_tanggal_mulai' => '2025-03-12',
                'lomba_tanggal_selesai' => '2025-03-15',
                'lomba_link_pendaftaran' => 'https://strosin.com/autem-et-sit-beatae-id.html',
                'lomba_link_poster' => 'https://placeimg.com/640/480',
            ],
            [
                'tingkatan_id' => 5,
                'semester_id' => 7,
                'lomba_nama' => 'Cybersecurity Competition',
                'lomba_penyelenggara' => 'Binus University',
                'lomba_kategori' => 'Cybersecurity',
                'lomba_tanggal_mulai' => '2024-08-30',
                'lomba_tanggal_selesai' => '2024-09-03',
                'lomba_link_pendaftaran' => 'http://gorczany.org/enim-nostrum-dolor-rerum-veritatis-autem-et.html',
                'lomba_link_poster' => 'https://placeimg.com/640/480',
            ],
            [
                'tingkatan_id' => 5,
                'semester_id' => 7,
                'lomba_nama' => 'MySQL Developer',
                'lomba_penyelenggara' => 'Universitas Brawijaya',
                'lomba_kategori' => 'Software Testing',
                'lomba_tanggal_mulai' => '2024-09-26',
                'lomba_tanggal_selesai' => '2024-10-03',
                'lomba_link_pendaftaran' => 'http://okeefe.org/facilis-velit-nisi-architecto.html',
                'lomba_link_poster' => 'https://placeimg.com/640/480',
            ],
            [
                'tingkatan_id' => 1,
                'semester_id' => 7,
                'lomba_nama' => 'IoT Developer',
                'lomba_penyelenggara' => 'Google Developer Group',
                'lomba_kategori' => 'Mobile App',
                'lomba_tanggal_mulai' => '2024-08-01',
                'lomba_tanggal_selesai' => '2024-08-07',
                'lomba_link_pendaftaran' => 'https://towne.com/possimus-et-exercitationem-dolorum-in-nemo-vero.html',
                'lomba_link_poster' => 'https://placeimg.com/640/480',
            ],
            [
                'tingkatan_id' => 3,
                'semester_id' => 7,
                'lomba_nama' => 'AI Innovation Challenge',
                'lomba_penyelenggara' => 'Universitas Indonesia',
                'lomba_kategori' => 'Artificial Intelligence',
                'lomba_tanggal_mulai' => '2024-09-10',
                'lomba_tanggal_selesai' => '2024-09-15',
                'lomba_link_pendaftaran' => 'https://aiui.id/daftar',
                'lomba_link_poster' => 'https://placeimg.com/640/480',
            ],
            [
                'tingkatan_id' => 2,
                'semester_id' => 7,
                'lomba_nama' => 'Database Design Contest',
                'lomba_penyelenggara' => 'Oracle Academy',
                'lomba_kategori' => 'Database',
                'lomba_tanggal_mulai' => '2024-10-20',
                'lomba_tanggal_selesai' => '2024-10-25',
                'lomba_link_pendaftaran' => 'https://oracleacademy.com/db-contest',
                'lomba_link_poster' => 'https://placeimg.com/640/480',
            ],
            [
                'tingkatan_id' => 4,
                'semester_id' => 7,
                'lomba_nama' => 'Frontend Developer Fest',
                'lomba_penyelenggara' => 'ReactJS Indonesia',
                'lomba_kategori' => 'Frontend',
                'lomba_tanggal_mulai' => '2025-01-05',
                'lomba_tanggal_selesai' => '2025-01-10',
                'lomba_link_pendaftaran' => 'https://reactjs.id/lomba-frontend',
                'lomba_link_poster' => 'https://placeimg.com/640/480',
            ],
            [
                'tingkatan_id' => 1,
                'semester_id' => 7,
                'lomba_nama' => 'Startup Ideathon',
                'lomba_penyelenggara' => 'StartupHub Asia',
                'lomba_kategori' => 'Entrepreneurship',
                'lomba_tanggal_mulai' => '2024-12-01',
                'lomba_tanggal_selesai' => '2024-12-05',
                'lomba_link_pendaftaran' => 'https://startuphub.asia/ideathon',
                'lomba_link_poster' => 'https://placeimg.com/640/480',
            ],
            [
                'tingkatan_id' => 5,
                'semester_id' => 7,
                'lomba_nama' => 'Project Manager',
                'lomba_penyelenggara' => 'GameDev.ID',
                'lomba_kategori' => 'Game Development',
                'lomba_tanggal_mulai' => '2024-11-11',
                'lomba_tanggal_selesai' => '2024-11-18',
                'lomba_link_pendaftaran' => 'https://gamedev.id/jam2024',
                'lomba_link_poster' => 'https://placeimg.com/640/480',
            ],
            [
                'tingkatan_id' => 3,
                'semester_id' => 7,
                'lomba_nama' => 'Cloud Computing Challenge',
                'lomba_penyelenggara' => 'AWS Educate',
                'lomba_kategori' => 'Cloud Computing',
                'lomba_tanggal_mulai' => '2024-09-21',
                'lomba_tanggal_selesai' => '2024-09-30',
                'lomba_link_pendaftaran' => 'https://awseducate.com/challenge',
                'lomba_link_poster' => 'https://placeimg.com/640/480',
            ],
            [
                'tingkatan_id' => 4,
                'semester_id' => 8,
                'lomba_nama' => 'AI and Robotics Expo',
                'lomba_penyelenggara' => 'BRIN',
                'lomba_kategori' => 'Robotics',
                'lomba_tanggal_mulai' => '2025-02-10',
                'lomba_tanggal_selesai' => '2025-02-14',
                'lomba_link_pendaftaran' => 'https://brin.go.id/robotik',
                'lomba_link_poster' => 'https://placeimg.com/640/480',
            ],
            [
                'tingkatan_id' => 2,
                'semester_id' => 7,
                'lomba_nama' => 'Hackathon Cyber Patriot',
                'lomba_penyelenggara' => 'Kemenkominfo',
                'lomba_kategori' => 'Cybersecurity',
                'lomba_tanggal_mulai' => '2024-08-20',
                'lomba_tanggal_selesai' => '2024-08-24',
                'lomba_link_pendaftaran' => 'https://kominfo.go.id/hackathon2024',
                'lomba_link_poster' => 'https://placeimg.com/640/480',
            ],
            [
                'tingkatan_id' => 1,
                'semester_id' => 7,
                'lomba_nama' => 'Beginner Coding Race',
                'lomba_penyelenggara' => 'Dicoding',
                'lomba_kategori' => 'Competitive Programming',
                'lomba_tanggal_mulai' => '2024-07-15',
                'lomba_tanggal_selesai' => '2024-07-20',
                'lomba_link_pendaftaran' => 'https://dicoding.com/lomba-beginner',
                'lomba_link_poster' => 'https://placeimg.com/640/480',
            ],
            [
                'tingkatan_id' => 5,
                'semester_id' => 7,
                'lomba_nama' => 'National Software Engineering Cup',
                'lomba_penyelenggara' => 'Puspresnas',
                'lomba_kategori' => 'Software Engineering',
                'lomba_tanggal_mulai' => '2024-10-05',
                'lomba_tanggal_selesai' => '2024-10-10',
                'lomba_link_pendaftaran' => 'https://puspresnas.kemdikbud.go.id/lomba-software',
                'lomba_link_poster' => 'https://placeimg.com/640/480',
            ],
        ]);
    }
}
