<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class LombaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('m_lombas')->insert([
            [
                'tingkatan_id' => 2,
                'semester_id' => 7,
                'lomba_nama' => 'Lomba Frontend Web Design',
                'lomba_penyelenggara' => 'Dicoding',
                'lomba_kategori' => 'Akademik',
                'lomba_tanggal_mulai' => '2024-09-01',
                'lomba_tanggal_selesai' => '2024-09-05',
                'lomba_link_pendaftaran' => '',
                'lomba_link_poster' => '',
                'lomba_terverifikasi' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 3,
                'semester_id' => 8,
                'lomba_nama' => 'Backend API Development Contest',
                'lomba_penyelenggara' => 'PENS',
                'lomba_kategori' => 'Akademik',
                'lomba_tanggal_mulai' => '2025-04-10',
                'lomba_tanggal_selesai' => '2025-04-15',
                'lomba_link_pendaftaran' => '',
                'lomba_link_poster' => '',
                'lomba_terverifikasi' => false,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 2,
                'semester_id' => 8,
                'lomba_nama' => 'Indie Game Development Jam',
                'lomba_penyelenggara' => 'GameDev Indonesia',
                'lomba_kategori' => 'Non-Akademik',
                'lomba_tanggal_mulai' => '2025-07-01',
                'lomba_tanggal_selesai' => '2025-07-10',
                'lomba_link_pendaftaran' => '',
                'lomba_link_poster' => '',
                'lomba_terverifikasi' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 1,
                'semester_id' => 7,
                'lomba_nama' => 'React Developer',
                'lomba_penyelenggara' => 'Kominfo',
                'lomba_kategori' => 'Akademik',
                'lomba_tanggal_mulai' => '2024-10-17',
                'lomba_tanggal_selesai' => '2024-10-22',
                'lomba_link_pendaftaran' => 'https://reyes.com/sint-et-libero-maxime-delectus.html',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 5,
                'semester_id' => 7,
                'lomba_nama' => 'Android Developer',
                'lomba_penyelenggara' => 'Telkom University',
                'lomba_kategori' => 'Akademik',
                'lomba_tanggal_mulai' => '2024-10-03',
                'lomba_tanggal_selesai' => '2024-10-13',
                'lomba_link_pendaftaran' => 'http://zemlak.com/autem-est-enim-aut-autem-non.html',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => false,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 1,
                'semester_id' => 7,
                'lomba_nama' => 'UI/UX Designer',
                'lomba_penyelenggara' => 'ITS Surabaya',
                'lomba_kategori' => 'Non-Akademik',
                'lomba_tanggal_mulai' => '2024-11-28',
                'lomba_tanggal_selesai' => '2024-12-07',
                'lomba_link_pendaftaran' => 'https://jast.org/delectus-mollitia-at-et-voluptatem-ut-ut.html',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 4,
                'semester_id' => 7,
                'lomba_nama' => 'Graphic Designer',
                'lomba_penyelenggara' => 'Dicoding',
                'lomba_kategori' => 'Non-Akademik',
                'lomba_tanggal_mulai' => '2024-10-15',
                'lomba_tanggal_selesai' => '2024-10-18',
                'lomba_link_pendaftaran' => 'http://mraz.com/exercitationem-explicabo-deleniti-qui-nobis-ipsum.html',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => false,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 4,
                'semester_id' => 7,
                'lomba_nama' => 'Data Scientist',
                'lomba_penyelenggara' => 'Polinema',
                'lomba_kategori' => 'Akademik',
                'lomba_tanggal_mulai' => '2025-01-11',
                'lomba_tanggal_selesai' => '2025-01-16',
                'lomba_link_pendaftaran' => 'https://macejkovic.com/qui-voluptatibus-eum-iusto-sit-et-eum-est.html',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 5,
                'semester_id' => 7,
                'lomba_nama' => 'Java Developer',
                'lomba_penyelenggara' => 'Polinema',
                'lomba_kategori' => 'Akademik',
                'lomba_tanggal_mulai' => '2024-11-03',
                'lomba_tanggal_selesai' => '2024-11-13',
                'lomba_link_pendaftaran' => 'https://schmidt.com/exercitationem-reiciendis-molestiae.html',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 2,
                'semester_id' => 7,
                'lomba_nama' => 'Python Developer',
                'lomba_penyelenggara' => 'Microsoft Indonesia',
                'lomba_kategori' => 'Non-Akademik',
                'lomba_tanggal_mulai' => '2025-03-12',
                'lomba_tanggal_selesai' => '2025-03-15',
                'lomba_link_pendaftaran' => 'https://strosin.com/autem-et-sit-beatae-id.html',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => false,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 5,
                'semester_id' => 7,
                'lomba_nama' => 'Cybersecurity Competition',
                'lomba_penyelenggara' => 'Binus University',
                'lomba_kategori' => 'Akademik',
                'lomba_tanggal_mulai' => '2024-08-30',
                'lomba_tanggal_selesai' => '2024-09-03',
                'lomba_link_pendaftaran' => 'http://gorczany.org/enim-nostrum-dolor-rerum-veritatis-autem-et.html',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 5,
                'semester_id' => 7,
                'lomba_nama' => 'MySQL Developer',
                'lomba_penyelenggara' => 'Universitas Brawijaya',
                'lomba_kategori' => 'Akademik',
                'lomba_tanggal_mulai' => '2024-09-26',
                'lomba_tanggal_selesai' => '2024-10-03',
                'lomba_link_pendaftaran' => 'http://okeefe.org/facilis-velit-nisi-architecto.html',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => false,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 1,
                'semester_id' => 7,
                'lomba_nama' => 'IoT Developer',
                'lomba_penyelenggara' => 'Google Developer Group',
                'lomba_kategori' => 'Non-Akademik',
                'lomba_tanggal_mulai' => '2024-08-01',
                'lomba_tanggal_selesai' => '2024-08-07',
                'lomba_link_pendaftaran' => 'https://towne.com/possimus-et-exercitationem-dolorum-in-nemo-vero.html',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 3,
                'semester_id' => 7,
                'lomba_nama' => 'AI Innovation Challenge',
                'lomba_penyelenggara' => 'Universitas Indonesia',
                'lomba_kategori' => 'Akademik',
                'lomba_tanggal_mulai' => '2024-09-10',
                'lomba_tanggal_selesai' => '2024-09-15',
                'lomba_link_pendaftaran' => 'https://aiui.id/daftar',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 2,
                'semester_id' => 7,
                'lomba_nama' => 'Database Design Contest',
                'lomba_penyelenggara' => 'Oracle Academy',
                'lomba_kategori' => 'Akademik',
                'lomba_tanggal_mulai' => '2024-10-20',
                'lomba_tanggal_selesai' => '2024-10-25',
                'lomba_link_pendaftaran' => 'https://oracleacademy.com/db-contest',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => false,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 4,
                'semester_id' => 7,
                'lomba_nama' => 'Frontend Developer Fest',
                'lomba_penyelenggara' => 'ReactJS Indonesia',
                'lomba_kategori' => 'Non-Akademik',
                'lomba_tanggal_mulai' => '2025-01-05',
                'lomba_tanggal_selesai' => '2025-01-10',
                'lomba_link_pendaftaran' => 'https://reactjs.id/lomba-frontend',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 1,
                'semester_id' => 7,
                'lomba_nama' => 'Startup Ideathon',
                'lomba_penyelenggara' => 'StartupHub Asia',
                'lomba_kategori' => 'Non-Akademik',
                'lomba_tanggal_mulai' => '2024-12-01',
                'lomba_tanggal_selesai' => '2024-12-05',
                'lomba_link_pendaftaran' => 'https://startuphub.asia/ideathon',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => false,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 5,
                'semester_id' => 7,
                'lomba_nama' => 'Project Manager',
                'lomba_penyelenggara' => 'GameDev.ID',
                'lomba_kategori' => 'Non-Akademik',
                'lomba_tanggal_mulai' => '2024-11-11',
                'lomba_tanggal_selesai' => '2024-11-18',
                'lomba_link_pendaftaran' => 'https://gamedev.id/jam2024',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 3,
                'semester_id' => 7,
                'lomba_nama' => 'Cloud Computing Challenge',
                'lomba_penyelenggara' => 'AWS Educate',
                'lomba_kategori' => 'Akademik',
                'lomba_tanggal_mulai' => '2024-09-21',
                'lomba_tanggal_selesai' => '2024-09-30',
                'lomba_link_pendaftaran' => 'https://awseducate.com/challenge',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 4,
                'semester_id' => 8,
                'lomba_nama' => 'AI and Robotics Expo',
                'lomba_penyelenggara' => 'BRIN',
                'lomba_kategori' => 'Akademik',
                'lomba_tanggal_mulai' => '2025-02-10',
                'lomba_tanggal_selesai' => '2025-02-14',
                'lomba_link_pendaftaran' => 'https://brin.go.id/robotik',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => false,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 2,
                'semester_id' => 7,
                'lomba_nama' => 'Hackathon Cyber Patriot',
                'lomba_penyelenggara' => 'Kemenkominfo',
                'lomba_kategori' => 'Akademik',
                'lomba_tanggal_mulai' => '2024-08-20',
                'lomba_tanggal_selesai' => '2024-08-24',
                'lomba_link_pendaftaran' => 'https://kominfo.go.id/hackathon2024',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 1,
                'semester_id' => 7,
                'lomba_nama' => 'Beginner Coding Race',
                'lomba_penyelenggara' => 'Dicoding',
                'lomba_kategori' => 'Non-Akademik',
                'lomba_tanggal_mulai' => '2024-07-15',
                'lomba_tanggal_selesai' => '2024-07-20',
                'lomba_link_pendaftaran' => 'https://dicoding.com/lomba-beginner',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 5,
                'semester_id' => 7,
                'lomba_nama' => 'National Software Engineering Cup',
                'lomba_penyelenggara' => 'Puspresnas',
                'lomba_kategori' => 'Akademik',
                'lomba_tanggal_mulai' => '2024-10-05',
                'lomba_tanggal_selesai' => '2024-10-10',
                'lomba_link_pendaftaran' => 'https://puspresnas.kemdikbud.go.id/lomba-software',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => false,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 5,
                'semester_id' => 7,
                'lomba_nama' => 'National Software Engineering Cup',
                'lomba_penyelenggara' => 'Puspresnas',
                'lomba_kategori' => 'Akademik',
                'lomba_tanggal_mulai' => '2024-10-05',
                'lomba_tanggal_selesai' => '2024-10-10',
                'lomba_link_pendaftaran' => 'https://puspresnas.kemdikbud.go.id/lomba-software',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => false,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 2,
                'semester_id' => 7,
                'lomba_nama' => 'Mobile App Innovation Contest',
                'lomba_penyelenggara' => 'Google Developer Indonesia',
                'lomba_kategori' => 'Akademik',
                'lomba_tanggal_mulai' => '2025-06-15',
                'lomba_tanggal_selesai' => '2025-06-20',
                'lomba_link_pendaftaran' => 'https://developers.google.com/mobile-contest',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 3,
                'semester_id' => 8,
                'lomba_nama' => 'Blockchain Development Challenge',
                'lomba_penyelenggara' => 'Ethereum Foundation',
                'lomba_kategori' => 'Non-Akademik',
                'lomba_tanggal_mulai' => '2025-05-10',
                'lomba_tanggal_selesai' => '2025-08-17',
                'lomba_link_pendaftaran' => 'https://ethereum.org/blockchain-challenge',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => false,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 1,
                'semester_id' => 7,
                'lomba_nama' => 'WordPress Theme Design Contest',
                'lomba_penyelenggara' => 'WordPress Community',
                'lomba_kategori' => 'Non-Akademik',
                'lomba_tanggal_mulai' => '2025-05-05',
                'lomba_tanggal_selesai' => '2025-09-12',
                'lomba_link_pendaftaran' => 'https://wordpress.org/theme-contest',
                'lomba_link_poster' => '',
                'lomba_terverifikasi' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 4,
                'semester_id' => 7,
                'lomba_nama' => 'Machine Learning Hackathon',
                'lomba_penyelenggara' => 'Kaggle',
                'lomba_kategori' => 'Akademik',
                'lomba_tanggal_mulai' => '2025-05-22',
                'lomba_tanggal_selesai' => '2025-07-29',
                'lomba_link_pendaftaran' => 'https://kaggle.com/ml-hackathon',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 5,
                'semester_id' => 8,
                'lomba_nama' => 'Enterprise Software Development',
                'lomba_penyelenggara' => 'Microsoft Azure',
                'lomba_kategori' => 'Akademik',
                'lomba_tanggal_mulai' => '2025-5-14',
                'lomba_tanggal_selesai' => '2025-10-21',
                'lomba_link_pendaftaran' => 'https://azure.microsoft.com/enterprise-dev',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => false,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 2,
                'semester_id' => 7,
                'lomba_nama' => 'CSS Animation Challenge',
                'lomba_penyelenggara' => 'CodePen',
                'lomba_kategori' => 'Non-Akademik',
                'lomba_tanggal_mulai' => '2025-11-08',
                'lomba_tanggal_selesai' => '2025-11-15',
                'lomba_link_pendaftaran' => 'https://codepen.io/css-challenge',
                'lomba_link_poster' => '',
                'lomba_terverifikasi' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 3,
                'semester_id' => 7,
                'lomba_nama' => 'API Design Competition',
                'lomba_penyelenggara' => 'Postman',
                'lomba_kategori' => 'Akademik',
                'lomba_tanggal_mulai' => '2025-12-03',
                'lomba_tanggal_selesai' => '2025-12-10',
                'lomba_link_pendaftaran' => 'https://postman.com/api-design',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 1,
                'semester_id' => 8,
                'lomba_nama' => 'Digital Art & Design Showcase',
                'lomba_penyelenggara' => 'Adobe Creative Cloud',
                'lomba_kategori' => 'Non-Akademik',
                'lomba_tanggal_mulai' => '2026-01-15',
                'lomba_tanggal_selesai' => '2026-01-22',
                'lomba_link_pendaftaran' => 'https://adobe.com/digital-art-showcase',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => false,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 4,
                'semester_id' => 8,
                'lomba_nama' => 'DevOps Excellence Award',
                'lomba_penyelenggara' => 'Docker Inc',
                'lomba_kategori' => 'Akademik',
                'lomba_tanggal_mulai' => '2026-02-12',
                'lomba_tanggal_selesai' => '2026-02-19',
                'lomba_link_pendaftaran' => 'https://docker.com/devops-award',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 5,
                'semester_id' => 7,
                'lomba_nama' => 'Quantum Computing Challenge',
                'lomba_penyelenggara' => 'IBM Quantum',
                'lomba_kategori' => 'Akademik',
                'lomba_tanggal_mulai' => '2026-03-20',
                'lomba_tanggal_selesai' => '2026-03-27',
                'lomba_link_pendaftaran' => 'https://quantum-computing.ibm.com/challenge',
                'lomba_link_poster' => '',
                'lomba_terverifikasi' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 2,
                'semester_id' => 8,
                'lomba_nama' => 'React Native App Contest',
                'lomba_penyelenggara' => 'Facebook Developer',
                'lomba_kategori' => 'Non-Akademik',
                'lomba_tanggal_mulai' => '2026-04-18',
                'lomba_tanggal_selesai' => '2026-04-25',
                'lomba_link_pendaftaran' => 'https://developers.facebook.com/react-native',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => false,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 3,
                'semester_id' => 7,
                'lomba_nama' => 'Kubernetes Orchestration Challenge',
                'lomba_penyelenggara' => 'Cloud Native Computing Foundation',
                'lomba_kategori' => 'Akademik',
                'lomba_tanggal_mulai' => '2026-05-16',
                'lomba_tanggal_selesai' => '2026-05-23',
                'lomba_link_pendaftaran' => 'https://cncf.io/kubernetes-challenge',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 1,
                'semester_id' => 7,
                'lomba_nama' => 'Web Accessibility Challenge',
                'lomba_penyelenggara' => 'W3C Web Accessibility Initiative',
                'lomba_kategori' => 'Non-Akademik',
                'lomba_tanggal_mulai' => '2026-06-14',
                'lomba_tanggal_selesai' => '2026-06-21',
                'lomba_link_pendaftaran' => 'https://w3.org/accessibility-challenge',
                'lomba_link_poster' => '',
                'lomba_terverifikasi' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 4,
                'semester_id' => 8,
                'lomba_nama' => 'AR/VR Innovation Contest',
                'lomba_penyelenggara' => 'Unity Technologies',
                'lomba_kategori' => 'Akademik',
                'lomba_tanggal_mulai' => '2026-07-12',
                'lomba_tanggal_selesai' => '2026-07-19',
                'lomba_link_pendaftaran' => 'https://unity.com/ar-vr-contest',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => false,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 5,
                'semester_id' => 7,
                'lomba_nama' => 'Microservices Architecture Challenge',
                'lomba_penyelenggara' => 'Netflix Tech',
                'lomba_kategori' => 'Akademik',
                'lomba_tanggal_mulai' => '2026-08-10',
                'lomba_tanggal_selesai' => '2026-08-17',
                'lomba_link_pendaftaran' => 'https://netflix.com/microservices-challenge',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 2,
                'semester_id' => 8,
                'lomba_nama' => 'Progressive Web App Contest',
                'lomba_penyelenggara' => 'Google Chrome Team',
                'lomba_kategori' => 'Non-Akademik',
                'lomba_tanggal_mulai' => '2026-09-08',
                'lomba_tanggal_selesai' => '2026-09-15',
                'lomba_link_pendaftaran' => 'https://chrome.google.com/pwa-contest',
                'lomba_link_poster' => '',
                'lomba_terverifikasi' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 3,
                'semester_id' => 7,
                'lomba_nama' => 'GraphQL API Championship',
                'lomba_penyelenggara' => 'GraphQL Foundation',
                'lomba_kategori' => 'Akademik',
                'lomba_tanggal_mulai' => '2026-10-06',
                'lomba_tanggal_selesai' => '2026-10-13',
                'lomba_link_pendaftaran' => 'https://graphql.org/championship',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => false,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 1,
                'semester_id' => 8,
                'lomba_nama' => 'UI Component Library Challenge',
                'lomba_penyelenggara' => 'Storybook',
                'lomba_kategori' => 'Non-Akademik',
                'lomba_tanggal_mulai' => '2026-11-04',
                'lomba_tanggal_selesai' => '2026-11-11',
                'lomba_link_pendaftaran' => 'https://storybook.js.org/ui-challenge',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 4,
                'semester_id' => 7,
                'lomba_nama' => 'Edge Computing Innovation',
                'lomba_penyelenggara' => 'Cloudflare',
                'lomba_kategori' => 'Akademik',
                'lomba_tanggal_mulai' => '2026-12-02',
                'lomba_tanggal_selesai' => '2026-12-09',
                'lomba_link_pendaftaran' => 'https://cloudflare.com/edge-innovation',
                'lomba_link_poster' => '',
                'lomba_terverifikasi' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 5,
                'semester_id' => 8,
                'lomba_nama' => 'Distributed Systems Challenge',
                'lomba_penyelenggara' => 'Apache Software Foundation',
                'lomba_kategori' => 'Akademik',
                'lomba_tanggal_mulai' => '2027-01-14',
                'lomba_tanggal_selesai' => '2027-01-21',
                'lomba_link_pendaftaran' => 'https://apache.org/distributed-systems',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => false,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 2,
                'semester_id' => 7,
                'lomba_nama' => 'CSS Grid Layout Competition',
                'lomba_penyelenggara' => 'Mozilla Developer Network',
                'lomba_kategori' => 'Non-Akademik',
                'lomba_tanggal_mulai' => '2027-02-11',
                'lomba_tanggal_selesai' => '2027-02-18',
                'lomba_link_pendaftaran' => 'https://developer.mozilla.org/css-grid',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 3,
                'semester_id' => 8,
                'lomba_nama' => 'Serverless Architecture Contest',
                'lomba_penyelenggara' => 'AWS Lambda',
                'lomba_kategori' => 'Akademik',
                'lomba_tanggal_mulai' => '2027-03-11',
                'lomba_tanggal_selesai' => '2027-03-18',
                'lomba_link_pendaftaran' => 'https://aws.amazon.com/lambda/contest',
                'lomba_link_poster' => '',
                'lomba_terverifikasi' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 1,
                'semester_id' => 7,
                'lomba_nama' => 'Responsive Design Challenge',
                'lomba_penyelenggara' => 'Bootstrap Team',
                'lomba_kategori' => 'Non-Akademik',
                'lomba_tanggal_mulai' => '2027-04-08',
                'lomba_tanggal_selesai' => '2027-04-15',
                'lomba_link_pendaftaran' => 'https://getbootstrap.com/responsive-challenge',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => false,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 4,
                'semester_id' => 8,
                'lomba_nama' => 'Natural Language Processing Contest',
                'lomba_penyelenggara' => 'OpenAI',
                'lomba_kategori' => 'Akademik',
                'lomba_tanggal_mulai' => '2027-05-06',
                'lomba_tanggal_selesai' => '2027-05-13',
                'lomba_link_pendaftaran' => 'https://openai.com/nlp-contest',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 2,
                'semester_id' => 7,
                'lomba_nama' => 'TypeScript Advanced Patterns',
                'lomba_penyelenggara' => 'Microsoft TypeScript Team',
                'lomba_kategori' => 'Akademik',
                'lomba_tanggal_mulai' => '2027-06-10',
                'lomba_tanggal_selesai' => '2027-06-17',
                'lomba_link_pendaftaran' => 'https://typescriptlang.org/patterns-contest',
                'lomba_link_poster' => '',
                'lomba_terverifikasi' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 5,
                'semester_id' => 8,
                'lomba_nama' => 'Security Vulnerability Assessment',
                'lomba_penyelenggara' => 'OWASP Foundation',
                'lomba_kategori' => 'Akademik',
                'lomba_tanggal_mulai' => '2027-07-15',
                'lomba_tanggal_selesai' => '2027-07-22',
                'lomba_link_pendaftaran' => 'https://owasp.org/security-assessment',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => false,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'tingkatan_id' => 3,
                'semester_id' => 7,
                'lomba_nama' => 'Database Performance Optimization',
                'lomba_penyelenggara' => 'PostgreSQL Community',
                'lomba_kategori' => 'Non-Akademik',
                'lomba_tanggal_mulai' => '2027-08-12',
                'lomba_tanggal_selesai' => '2027-08-19',
                'lomba_link_pendaftaran' => 'https://postgresql.org/performance-contest',
                'lomba_link_poster' => 'https:///picsum.photos/640/480',
                'lomba_terverifikasi' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
        ]);
    }
}