<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class MahasiswaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('m_mahasiswas')->insert([
            [
                'user_id' => '12',
                'prodi_id' => 1,
                'keahlian_id' => '1',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Taufik Dimas Edystara',
                'mahasiswa_nim' => '2341720062',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Laki-laki',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '085730760115',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 5375,
                'mahasiswa_provinsi' => 'Jawa Timur',
                'mahasiswa_kota' => 'Malang',
                'mahasiswa_kecamatan' => 'Lowokwaru',
                'mahasiswa_desa' => 'Dinoyo',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '13',
                'prodi_id' => 1,
                'keahlian_id' => '2',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Noklent Fardian Erix',
                'mahasiswa_nim' => '2341720082',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Laki-laki',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '087866301810',
                'mahasiswa_photo'=>null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 5213,
                'mahasiswa_provinsi' => 'Jawa Timur',
                'mahasiswa_kota' => 'Surabaya',
                'mahasiswa_kecamatan' => 'Gubeng',
                'mahasiswa_desa' => 'Airlangga',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '14',
                'prodi_id' => 1,
                'keahlian_id' => '3',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Achmad Maulana Hamzah',
                'mahasiswa_nim' => '2341720172',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Laki-laki',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '082131973378',
                'mahasiswa_photo'=>null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 5500,
                'mahasiswa_provinsi' => 'Jawa Tengah',
                'mahasiswa_kota' => 'Semarang',
                'mahasiswa_kecamatan' => 'Tembalang',
                'mahasiswa_desa' => 'Tembalang',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '15',
                'prodi_id' => 1,
                'keahlian_id' => '4',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Necha Syifa Syafitri',
                'mahasiswa_nim' => '2341720167',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Perempuan',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '082133236984',
                'mahasiswa_photo'=>null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 10688,
                'mahasiswa_provinsi' => 'Jawa Barat',
                'mahasiswa_kota' => 'Bandung',
                'mahasiswa_kecamatan' => 'Coblong',
                'mahasiswa_desa' => 'Dago',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '16',
                'prodi_id' => 1,
                'keahlian_id' => '5',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Candra Ahmad Dani',
                'mahasiswa_nim' => '2341720187',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Laki-laki',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '089517032681',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 3625,
                'mahasiswa_provinsi' => 'DKI Jakarta',
                'mahasiswa_kota' => 'Jakarta Selatan',
                'mahasiswa_kecamatan' => 'Kebayoran Baru',
                'mahasiswa_desa' => 'Senayan',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '17',
                'prodi_id' => 1,
                'keahlian_id' => '1',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Hendra Ujang',
                'mahasiswa_nim' => '2341720935',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Laki-laki',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08346019704',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 1150,
                'mahasiswa_provinsi' => 'Jawa Timur',
                'mahasiswa_kota' => 'Malang',
                'mahasiswa_kecamatan' => 'Klojen',
                'mahasiswa_desa' => 'Kauman',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '18',
                'prodi_id' => 1,
                'keahlian_id' => '2',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Maya Tiara',
                'mahasiswa_nim' => '2341720643',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Perempuan',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08212822889',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 1625,
                'mahasiswa_provinsi' => 'Yogyakarta',
                'mahasiswa_kota' => 'Yogyakarta',
                'mahasiswa_kecamatan' => 'Depok',
                'mahasiswa_desa' => 'Caturtunggal',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '19',
                'prodi_id' => 1,
                'keahlian_id' => '4',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Putra Nugroho',
                'mahasiswa_nim' => '2341720397',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Laki-laki',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08123347264',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 1250,
                'mahasiswa_provinsi' => 'Jawa Timur',
                'mahasiswa_kota' => 'Pasuruan',
                'mahasiswa_kecamatan' => 'Bangil',
                'mahasiswa_desa' => 'Pogar',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '20',
                'prodi_id' => 1,
                'keahlian_id' => '5',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Eka Putri',
                'mahasiswa_nim' => '2341720422',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Perempuan',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08135189360',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 1625,
                'mahasiswa_provinsi' => 'Jawa Barat',
                'mahasiswa_kota' => 'Bogor',
                'mahasiswa_kecamatan' => 'Bogor Tengah',
                'mahasiswa_desa' => 'Paledang',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '21',
                'prodi_id' => 1,
                'keahlian_id' => '2',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Wahyu Joko',
                'mahasiswa_nim' => '2341720499',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Laki-laki',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08529387530',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Konghucu',
                'mahasiswa_score' => 500,
                'mahasiswa_provinsi' => 'Banten',
                'mahasiswa_kota' => 'Tangerang',
                'mahasiswa_kecamatan' => 'Karawaci',
                'mahasiswa_desa' => 'Bencongan',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '22',
                'prodi_id' => 1,
                'keahlian_id' => '5',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Sari Kartika',
                'mahasiswa_nim' => '2341720870',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Perempuan',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08269316689',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Buddha',
                'mahasiswa_score' => 1500,
                'mahasiswa_provinsi' => 'Sumatera Utara',
                'mahasiswa_kota' => 'Medan',
                'mahasiswa_kecamatan' => 'Medan Timur',
                'mahasiswa_desa' => 'Simpang Limun',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '23',
                'prodi_id' => 1,
                'keahlian_id' => '2',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Lukman Rizky',
                'mahasiswa_nim' => '2341720049',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Laki-laki',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08222383094',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Konghucu',
                'mahasiswa_score' => 3750,
                'mahasiswa_provinsi' => 'Jawa Timur',
                'mahasiswa_kota' => 'Sidoarjo',
                'mahasiswa_kecamatan' => 'Waru',
                'mahasiswa_desa' => 'Waru',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '24',
                'prodi_id' => 1,
                'keahlian_id' => '1',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Eka Utami',
                'mahasiswa_nim' => '2341720628',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Perempuan',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08516519742',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 1000,
                'mahasiswa_provinsi' => 'Jawa Timur',
                'mahasiswa_kota' => 'Blitar',
                'mahasiswa_kecamatan' => 'Sananwetan',
                'mahasiswa_desa' => 'Plosoarang',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '25',
                'prodi_id' => 2,
                'keahlian_id' => '2',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Nugroho Cahyo',
                'mahasiswa_nim' => '2341790001',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Laki-laki',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08713719380',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Konghucu',
                'mahasiswa_score' => 375,
                'mahasiswa_provinsi' => 'Jawa Tengah',
                'mahasiswa_kota' => 'Solo',
                'mahasiswa_kecamatan' => 'Banjarsari',
                'mahasiswa_desa' => 'Keprabon',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '26',
                'prodi_id' => 2,
                'keahlian_id' => '5',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Putri Bella',
                'mahasiswa_nim' => '2341720137',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Perempuan',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08216578289',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 1250,
                'mahasiswa_provinsi' => 'Jawa Barat',
                'mahasiswa_kota' => 'Depok',
                'mahasiswa_kecamatan' => 'Pancoran Mas',
                'mahasiswa_desa' => 'Depok',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '27',
                'prodi_id' => 2,
                'keahlian_id' => '3',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Maulana Dedi',
                'mahasiswa_nim' => '2341720895',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Laki-laki',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08742248562',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 2250,
                'mahasiswa_provinsi' => 'Sumatera Barat',
                'mahasiswa_kota' => 'Padang',
                'mahasiswa_kecamatan' => 'Padang Utara',
                'mahasiswa_desa' => 'Air Tawar',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '28',
                'prodi_id' => 2,
                'keahlian_id' => '5',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Ayu Tiara',
                'mahasiswa_nim' => '2341720159',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Perempuan',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08588197914',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 1000,
                'mahasiswa_provinsi' => 'Bali',
                'mahasiswa_kota' => 'Denpasar',
                'mahasiswa_kecamatan' => 'Denpasar Timur',
                'mahasiswa_desa' => 'Kesiman',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '29',
                'prodi_id' => 1,
                'keahlian_id' => '1',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Hendra Eko',
                'mahasiswa_nim' => '2341720267',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Laki-laki',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08789057608',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Kalimantan Timur',
                'mahasiswa_kota' => 'Balikpapan',
                'mahasiswa_kecamatan' => 'Balikpapan Tengah',
                'mahasiswa_desa' => 'Damai',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '30',
                'prodi_id' => 1,
                'keahlian_id' => '4',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Tiara Ayu',
                'mahasiswa_nim' => '2341720782',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Perempuan',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08295633234',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Sulawesi Selatan',
                'mahasiswa_kota' => 'Makassar',
                'mahasiswa_kecamatan' => 'Tamalate',
                'mahasiswa_desa' => 'Mangasa',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '31',
                'prodi_id' => 1,
                'keahlian_id' => '4',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Iqbal Joko',
                'mahasiswa_nim' => '2341720026',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Laki-laki',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08916096280',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Buddha',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Jawa Timur',
                'mahasiswa_kota' => 'Mojokerto',
                'mahasiswa_kecamatan' => 'Kranggan',
                'mahasiswa_desa' => 'Sukosari',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '32',
                'prodi_id' => 1,
                'keahlian_id' => '2',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Tiara Sari',
                'mahasiswa_nim' => '2341720312',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Perempuan',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08309549617',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Jawa Barat',
                'mahasiswa_kota' => 'Bandung',
                'mahasiswa_kecamatan' => 'Sumurbandung',
                'mahasiswa_desa' => 'Cikawao',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '33',
                'prodi_id' => 1,
                'keahlian_id' => '2',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Kurniawan Rizky',
                'mahasiswa_nim' => '2341720353',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Laki-laki',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08735891938',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Hindu',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Jawa Timur',
                'mahasiswa_kota' => 'Kediri',
                'mahasiswa_kecamatan' => 'Kota Kediri',
                'mahasiswa_desa' => 'Mojoroto',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '34',
                'prodi_id' => 1,
                'keahlian_id' => '4',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Gita Wulan',
                'mahasiswa_nim' => '2341720683',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Perempuan',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08715801383',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Kristen',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Jawa Tengah',
                'mahasiswa_kota' => 'Semarang',
                'mahasiswa_kecamatan' => 'Semarang Tengah',
                'mahasiswa_desa' => 'Pekunden',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '35',
                'prodi_id' => 2,
                'keahlian_id' => '4',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Fajar Dedi',
                'mahasiswa_nim' => '2341720153',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Laki-laki',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08107924450',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Kristen',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Jawa Timur',
                'mahasiswa_kota' => 'Mojokerto',
                'mahasiswa_kecamatan' => 'Sooko',
                'mahasiswa_desa' => 'Jatirejo',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '36',
                'prodi_id' => 2,
                'keahlian_id' => '4',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Rani Gita',
                'mahasiswa_nim' => '2341720596',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Perempuan',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08583490489',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Jawa Barat',
                'mahasiswa_kota' => 'Bandung',
                'mahasiswa_kecamatan' => 'Sumurbandung',
                'mahasiswa_desa' => 'Cikawao',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '37',
                'prodi_id' => 2,
                'keahlian_id' => '1',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Dedi Joko',
                'mahasiswa_nim' => '2341720118',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Laki-laki',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08280966924',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Jawa Timur',
                'mahasiswa_kota' => 'Mojokerto',
                'mahasiswa_kecamatan' => 'Kranggan',
                'mahasiswa_desa' => 'Sukosari',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '38',
                'prodi_id' => 2,
                'keahlian_id' => '5',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Hani Indah',
                'mahasiswa_nim' => '2341720214',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Perempuan',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08183812502',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Jawa Tengah',
                'mahasiswa_kota' => 'Semarang',
                'mahasiswa_kecamatan' => 'Semarang Timur',
                'mahasiswa_desa' => 'Pekunden',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '39',
                'prodi_id' => 1,
                'keahlian_id' => '5',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Eko Lukman',
                'mahasiswa_nim' => '2341720941',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Laki-laki',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08594638453',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Buddha',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Jawa Timur',
                'mahasiswa_kota' => 'Mojokerto',
                'mahasiswa_kecamatan' => 'Kota Mojokerto',
                'mahasiswa_desa' => 'Kranggan',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '40',
                'prodi_id' => 2,
                'keahlian_id' => '3',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Ayu Juwita',
                'mahasiswa_nim' => '2341720204',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Perempuan',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08248421725',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Jawa Barat',
                'mahasiswa_kota' => 'Bandung',
                'mahasiswa_kecamatan' => 'Sumurbandung',
                'mahasiswa_desa' => 'Cikawao',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '41',
                'prodi_id' => 2,
                'keahlian_id' => '4',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Lukman Budi',
                'mahasiswa_nim' => '2341720289',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Laki-laki',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08728235609',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Jawa Timur',
                'mahasiswa_kota' => 'Mojokerto',
                'mahasiswa_kecamatan' => 'Kota Mojokerto',
                'mahasiswa_desa' => 'Kranggan',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '42',
                'prodi_id' => 1,
                'keahlian_id' => '1',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Citra Nadya',
                'mahasiswa_nim' => '2341720029',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Perempuan',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08560465227',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Jawa Timur',
                'mahasiswa_kota' => 'Mojokerto',
                'mahasiswa_kecamatan' => 'Kota Mojokerto',
                'mahasiswa_desa' => 'Kranggan',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '43',
                'prodi_id' => 2,
                'keahlian_id' => '4',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Lukman Hendra',
                'mahasiswa_nim' => '2341720679',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Laki-laki',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08790337922',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Jawa Timur',
                'mahasiswa_kota' => 'Mojokerto',
                'mahasiswa_kecamatan' => 'Kota Mojokerto',
                'mahasiswa_desa' => 'Kranggan',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '44',
                'prodi_id' => 2,
                'keahlian_id' => '2',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Ayu Gita',
                'mahasiswa_nim' => '2341720726',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Perempuan',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08575662324',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Konghucu',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Jawa Timur',
                'mahasiswa_kota' => 'Mojokerto',
                'mahasiswa_kecamatan' => 'Kota Mojokerto',
                'mahasiswa_desa' => 'Kranggan',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '45',
                'prodi_id' => 2,
                'keahlian_id' => '1',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Cahyo Gilang',
                'mahasiswa_nim' => '2341720686',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Laki-laki',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08150228031',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Jawa Timur',
                'mahasiswa_kota' => 'Mojokerto',
                'mahasiswa_kecamatan' => 'Kota Mojokerto',
                'mahasiswa_desa' => 'Kranggan',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '46',
                'prodi_id' => 2,
                'keahlian_id' => '2',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Fitri Gita',
                'mahasiswa_nim' => '2341720722',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Perempuan',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08167797000',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Jawa Timur',
                'mahasiswa_kota' => 'Mojokerto',
                'mahasiswa_kecamatan' => 'Kota Mojokerto',
                'mahasiswa_desa' => 'Kranggan',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '47',
                'prodi_id' => 1,
                'keahlian_id' => '4',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Eko Wahyu',
                'mahasiswa_nim' => '2341720472',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Laki-laki',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08559566894',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Konghucu',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Jawa Timur',
                'mahasiswa_kota' => 'Mojokerto',
                'mahasiswa_kecamatan' => 'Kota Mojokerto',
                'mahasiswa_desa' => 'Kranggan',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '48',
                'prodi_id' => 2,
                'keahlian_id' => '2',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Eka Indah',
                'mahasiswa_nim' => '2341720027',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Perempuan',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08900340012',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Jawa Timur',
                'mahasiswa_kota' => 'Mojokerto',
                'mahasiswa_kecamatan' => 'Kota Mojokerto',
                'mahasiswa_desa' => 'Kranggan',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '49',
                'prodi_id' => 2,
                'keahlian_id' => '1',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Agus Teguh',
                'mahasiswa_nim' => '2341720232',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Laki-laki',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08946691300',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Jawa Timur',
                'mahasiswa_kota' => 'Mojokerto',
                'mahasiswa_kecamatan' => 'Kota Mojokerto',
                'mahasiswa_desa' => 'Kranggan',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '50',
                'prodi_id' => 1,
                'keahlian_id' => '2',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Fitri Ayu',
                'mahasiswa_nim' => '2341720181',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Perempuan',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08957602555',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Jawa Timur',
                'mahasiswa_kota' => 'Mojokerto',
                'mahasiswa_kecamatan' => 'Kota Mojokerto',
                'mahasiswa_desa' => 'Kranggan',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '51',
                'prodi_id' => 2,
                'keahlian_id' => '2',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Kurniawan Maulana',
                'mahasiswa_nim' => '2341720271',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Laki-laki',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08320871027',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Konghucu',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Jawa Timur',
                'mahasiswa_kota' => 'Mojokerto',
                'mahasiswa_kecamatan' => 'Kota Mojokerto',
                'mahasiswa_desa' => 'Kranggan',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '52',
                'prodi_id' => 1,
                'keahlian_id' => '5',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Nadya Fitri',
                'mahasiswa_nim' => '2341720789',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Perempuan',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08239164895',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Jawa Timur',
                'mahasiswa_kota' => 'Mojokerto',
                'mahasiswa_kecamatan' => 'Kota Mojokerto',
                'mahasiswa_desa' => 'Kranggan',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '53',
                'prodi_id' => 2,
                'keahlian_id' => '5',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Wahyu Budi',
                'mahasiswa_nim' => '2341720790',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Laki-laki',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08596619899',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Jawa Timur',
                'mahasiswa_kota' => 'Mojokerto',
                'mahasiswa_kecamatan' => 'Kota Mojokerto',
                'mahasiswa_desa' => 'Kranggan',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '54',
                'prodi_id' => 1,
                'keahlian_id' => '4',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Indah Citra',
                'mahasiswa_nim' => '2341720210',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Perempuan',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08370897179',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Buddha',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Jawa Timur',
                'mahasiswa_kota' => 'Mojokerto',
                'mahasiswa_kecamatan' => 'Kota Mojokerto',
                'mahasiswa_desa' => 'Kranggan',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '55',
                'prodi_id' => 1,
                'keahlian_id' => '1',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Teguh Hendra',
                'mahasiswa_nim' => '2341720329',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Laki-laki',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08734345184',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Jawa Timur',
                'mahasiswa_kota' => 'Mojokerto',
                'mahasiswa_kecamatan' => 'Kota Mojokerto',
                'mahasiswa_desa' => 'Kranggan',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '56',
                'prodi_id' => 2,
                'keahlian_id' => '3',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Rani Juwita',
                'mahasiswa_nim' => '2341720361',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Perempuan',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08787364046',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Jawa Timur',
                'mahasiswa_kota' => 'Mojokerto',
                'mahasiswa_kecamatan' => 'Kota Mojokerto',
                'mahasiswa_desa' => 'Kranggan',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '57',
                'prodi_id' => 1,
                'keahlian_id' => '4',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Lukman Lukman',
                'mahasiswa_nim' => '2341720639',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Laki-laki',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08589977283',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Hindu',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Jawa Timur',
                'mahasiswa_kota' => 'Mojokerto',
                'mahasiswa_kecamatan' => 'Kota Mojokerto',
                'mahasiswa_desa' => 'Kranggan',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '58',
                'prodi_id' => 2,
                'keahlian_id' => '1',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Nadya Hani',
                'mahasiswa_nim' => '2341720168',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Perempuan',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08776156361',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Jawa Timur',
                'mahasiswa_kota' => 'Mojokerto',
                'mahasiswa_kecamatan' => 'Kota Mojokerto',
                'mahasiswa_desa' => 'Kranggan',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '59',
                'prodi_id' => 1,
                'keahlian_id' => '3',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Fajar Eko',
                'mahasiswa_nim' => '2341720199',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Laki-laki',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08246523666',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Jawa Timur',
                'mahasiswa_kota' => 'Mojokerto',
                'mahasiswa_kecamatan' => 'Kota Mojokerto',
                'mahasiswa_desa' => 'Kranggan',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '60',
                'prodi_id' => 2,
                'keahlian_id' => '3',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Maya Fitri',
                'mahasiswa_nim' => '2341720156',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Perempuan',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08760545803',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Jawa Timur',
                'mahasiswa_kota' => 'Mojokerto',
                'mahasiswa_kecamatan' => 'Kota Mojokerto',
                'mahasiswa_desa' => 'Kranggan',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '61',
                'prodi_id' => 1,
                'keahlian_id' => '1',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Rizky Gilang',
                'mahasiswa_nim' => '2341720163',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Laki-laki',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08190185937',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Jawa Timur',
                'mahasiswa_kota' => 'Mojokerto',
                'mahasiswa_kecamatan' => 'Kota Mojokerto',
                'mahasiswa_desa' => 'Kranggan',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '62',
                'prodi_id' => 2,
                'keahlian_id' => '3',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Gita Eka',
                'mahasiswa_nim' => '2341720897',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Perempuan',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08199292927',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Jawa Timur',
                'mahasiswa_kota' => 'Mojokerto',
                'mahasiswa_kecamatan' => 'Kota Mojokerto',
                'mahasiswa_desa' => 'Kranggan',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '63',
                'prodi_id' => 2,
                'keahlian_id' => '2',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Agus Putra',
                'mahasiswa_nim' => '2341720701',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Laki-laki',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08227362594',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Jawa Timur',
                'mahasiswa_kota' => 'Mojokerto',
                'mahasiswa_kecamatan' => 'Kota Mojokerto',
                'mahasiswa_desa' => 'Kranggan',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '64',
                'prodi_id' => 2,
                'keahlian_id' => '3',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Kartika Putri',
                'mahasiswa_nim' => '2341720061',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Perempuan',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08510914609',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Jawa Timur',
                'mahasiswa_kota' => 'Mojokerto',
                'mahasiswa_kecamatan' => 'Kota Mojokerto',
                'mahasiswa_desa' => 'Kranggan',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '65',
                'prodi_id' => 2,
                'keahlian_id' => '4',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Fajar Lukman',
                'mahasiswa_nim' => '2341720503',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Laki-laki',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08537613714',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Islam',
                'mahasiswa_score' => 0,
                'mahasiswa_provinsi' => 'Jawa Timur',
                'mahasiswa_kota' => 'Mojokerto',
                'mahasiswa_kecamatan' => 'Kota Mojokerto',
                'mahasiswa_desa' => 'Kranggan',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
            [
                'user_id' => '66',
                'prodi_id' => 2,
                'keahlian_id' => '1',
                'semester_id' => '8',
                'mahasiswa_nama' => 'Fitri Juwita',
                'mahasiswa_nim' => '2341720994',
                'mahasiswa_status' => 'Aktif',
                'mahasiswa_gender' => 'Perempuan',
                'mahasiswa_angkatan' => '2023',
                'mahasiswa_nomor_telepon' => '08712685873',
                'mahasiswa_photo' => null,
                'mahasiswa_agama' => 'Katolik',
                'mahasiswa_score' => 9850,
                'mahasiswa_provinsi' => 'Papua',
                'mahasiswa_kota' => 'Jayapura',
                'mahasiswa_kecamatan' => 'Jayapura Utara',
                'mahasiswa_desa' => 'Gurabesi',
                'mahasiswa_visible' => true,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::create(2025, 12, 31)->timestamp)),
            ],
        ]);
    }
}