<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class PenghargaanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('m_penghargaans')->insert([
            [
                'mahasiswa_id' => 1,
                'lomba_id' => 1,
                'peringkat_id' => 1,
                'tingkatan_id' => 2,
                'penghargaan_judul' => 'Juara 1 Lomba Frontend Web Design',
                'penghargaan_tempat' => 'Jakarta',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2024-09-01',
                'penghargaan_tanggal_selesai' => '2024-09-05',
                'penghargaan_jumlah_peserta' => 120,
                'penghargaan_jumlah_instansi' => 15,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2024-08-25',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 2250,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 2,
                'lomba_id' => 2,
                'peringkat_id' => 2,
                'tingkatan_id' => 3,
                'penghargaan_judul' => 'Juara 2 Backend API Development',
                'penghargaan_tempat' => 'Surabaya',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2025-04-10',
                'penghargaan_tanggal_selesai' => '2025-04-15',
                'penghargaan_jumlah_peserta' => 80,
                'penghargaan_jumlah_instansi' => 10,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2025-04-01',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 1250,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 3,
                'lomba_id' => 3,
                'peringkat_id' => 3,
                'tingkatan_id' => 2,
                'penghargaan_judul' => 'Juara 3 Indie Game Development Jam',
                'penghargaan_tempat' => 'Bandung',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2025-07-01',
                'penghargaan_tanggal_selesai' => '2025-07-10',
                'penghargaan_jumlah_peserta' => 60,
                'penghargaan_jumlah_instansi' => 8,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2025-06-25',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 1500,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 4,
                'lomba_id' => 4,
                'peringkat_id' => 4,
                'tingkatan_id' => 1,
                'penghargaan_judul' => 'Harapan 1 React Developer',
                'penghargaan_tempat' => 'Malang',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2024-10-17',
                'penghargaan_tanggal_selesai' => '2024-10-22',
                'penghargaan_jumlah_peserta' => 100,
                'penghargaan_jumlah_instansi' => 12,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2024-10-10',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 1500,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 5,
                'lomba_id' => 5,
                'peringkat_id' => 5,
                'tingkatan_id' => 5,
                'penghargaan_judul' => 'Harapan 2 Android Developer',
                'penghargaan_tempat' => 'Bandung',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2024-10-03',
                'penghargaan_tanggal_selesai' => '2024-10-13',
                'penghargaan_jumlah_peserta' => 90,
                'penghargaan_jumlah_instansi' => 9,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2024-09-28',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 125,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 1,
                'lomba_id' => 6,
                'peringkat_id' => 6,
                'tingkatan_id' => 1,
                'penghargaan_judul' => 'Harapan 3 UI/UX Designer',
                'penghargaan_tempat' => 'Surabaya',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2024-11-28',
                'penghargaan_tanggal_selesai' => '2024-12-07',
                'penghargaan_jumlah_peserta' => 70,
                'penghargaan_jumlah_instansi' => 7,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2024-11-20',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 1000,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 2,
                'lomba_id' => 7,
                'peringkat_id' => 1,
                'tingkatan_id' => 2,
                'penghargaan_judul' => 'Juara 1 Graphic Designer',
                'penghargaan_tempat' => 'Jakarta',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2024-10-15',
                'penghargaan_tanggal_selesai' => '2024-10-18',
                'penghargaan_jumlah_peserta' => 110,
                'penghargaan_jumlah_instansi' => 10,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2024-10-10',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 2250,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 8,
                'lomba_id' => 8,
                'peringkat_id' => 2,
                'tingkatan_id' => 3,
                'penghargaan_judul' => 'Juara 2 Data Scientist',
                'penghargaan_tempat' => 'Malang',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2025-01-11',
                'penghargaan_tanggal_selesai' => '2025-01-16',
                'penghargaan_jumlah_peserta' => 95,
                'penghargaan_jumlah_instansi' => 8,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2025-01-05',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 1250,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 2,
                'lomba_id' => 9,
                'peringkat_id' => 3,
                'tingkatan_id' => 4,
                'penghargaan_judul' => 'Juara 3 Java Developer',
                'penghargaan_tempat' => 'Bandung',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2024-11-03',
                'penghargaan_tanggal_selesai' => '2024-11-13',
                'penghargaan_jumlah_peserta' => 85,
                'penghargaan_jumlah_instansi' => 7,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2024-10-28',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 500,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 2,
                'lomba_id' => 10,
                'peringkat_id' => 4,
                'tingkatan_id' => 5,
                'penghargaan_judul' => 'Harapan 1 Python Developer',
                'penghargaan_tempat' => 'Surabaya',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2025-03-12',
                'penghargaan_tanggal_selesai' => '2025-03-15',
                'penghargaan_jumlah_peserta' => 75,
                'penghargaan_jumlah_instansi' => 6,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2025-03-01',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 150,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 2,
                'lomba_id' => 11,
                'peringkat_id' => 5,
                'tingkatan_id' => 2,
                'penghargaan_judul' => 'Harapan 2 Cybersecurity Competition',
                'penghargaan_tempat' => 'Jakarta',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2024-08-30',
                'penghargaan_tanggal_selesai' => '2024-09-03',
                'penghargaan_jumlah_peserta' => 130,
                'penghargaan_jumlah_instansi' => 14,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2024-08-20',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 938,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 11,
                'lomba_id' => 12,
                'peringkat_id' => 6,
                'tingkatan_id' => 3,
                'penghargaan_judul' => 'Harapan 3 MySQL Developer',
                'penghargaan_tempat' => 'Malang',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2024-09-26',
                'penghargaan_tanggal_selesai' => '2024-10-03',
                'penghargaan_jumlah_peserta' => 60,
                'penghargaan_jumlah_instansi' => 5,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2024-09-20',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 500,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 4,
                'lomba_id' => 13,
                'peringkat_id' => 1,
                'tingkatan_id' => 1,
                'penghargaan_judul' => 'Juara 1 IoT Developer',
                'penghargaan_tempat' => 'Jakarta',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2024-08-01',
                'penghargaan_tanggal_selesai' => '2024-08-07',
                'penghargaan_jumlah_peserta' => 50,
                'penghargaan_jumlah_instansi' => 4,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2024-07-25',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 3000,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 12,
                'lomba_id' => 14,
                'peringkat_id' => 2,
                'tingkatan_id' => 2,
                'penghargaan_judul' => 'Juara 2 AI Innovation Challenge',
                'penghargaan_tempat' => 'Surabaya',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2024-09-10',
                'penghargaan_tanggal_selesai' => '2024-09-15',
                'penghargaan_jumlah_peserta' => 70,
                'penghargaan_jumlah_instansi' => 6,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2024-09-01',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 1875,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 6,
                'lomba_id' => 15,
                'peringkat_id' => 3,
                'tingkatan_id' => 3,
                'penghargaan_judul' => 'Juara 3 Database Design Contest',
                'penghargaan_tempat' => 'Malang',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2024-10-20',
                'penghargaan_tanggal_selesai' => '2024-10-25',
                'penghargaan_jumlah_peserta' => 65,
                'penghargaan_jumlah_instansi' => 5,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2024-10-10',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 1000,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 7,
                'lomba_id' => 16,
                'peringkat_id' => 4,
                'tingkatan_id' => 4,
                'penghargaan_judul' => 'Harapan 1 Frontend Developer Fest',
                'penghargaan_tempat' => 'Bandung',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2025-01-05',
                'penghargaan_tanggal_selesai' => '2025-01-10',
                'penghargaan_jumlah_peserta' => 80,
                'penghargaan_jumlah_instansi' => 7,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2024-12-28',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 375,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 9,
                'lomba_id' => 17,
                'peringkat_id' => 5,
                'tingkatan_id' => 5,
                'penghargaan_judul' => 'Harapan 2 Startup Ideathon',
                'penghargaan_tempat' => 'Jakarta',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2024-12-01',
                'penghargaan_tanggal_selesai' => '2024-12-05',
                'penghargaan_jumlah_peserta' => 55,
                'penghargaan_jumlah_instansi' => 4,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2024-11-25',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 125,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 11,
                'lomba_id' => 18,
                'peringkat_id' => 6,
                'tingkatan_id' => 1,
                'penghargaan_judul' => 'Harapan 3 Project Manager',
                'penghargaan_tempat' => 'Surabaya',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2024-11-11',
                'penghargaan_tanggal_selesai' => '2024-11-18',
                'penghargaan_jumlah_peserta' => 60,
                'penghargaan_jumlah_instansi' => 5,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2024-11-01',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 1000,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 5,
                'lomba_id' => 19,
                'peringkat_id' => 1,
                'tingkatan_id' => 2,
                'penghargaan_judul' => 'Juara 1 Cloud Computing Challenge',
                'penghargaan_tempat' => 'Malang',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2024-09-21',
                'penghargaan_tanggal_selesai' => '2024-09-30',
                'penghargaan_jumlah_peserta' => 100,
                'penghargaan_jumlah_instansi' => 8,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2024-09-10',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 2250,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 7,
                'lomba_id' => 20,
                'peringkat_id' => 2,
                'tingkatan_id' => 3,
                'penghargaan_judul' => 'Juara 2 AI and Robotics Expo',
                'penghargaan_tempat' => 'Jakarta',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2025-02-10',
                'penghargaan_tanggal_selesai' => '2025-02-14',
                'penghargaan_jumlah_peserta' => 90,
                'penghargaan_jumlah_instansi' => 7,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2025-02-01',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 1250,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 16,
                'lomba_id' => 1,
                'peringkat_id' => 1,
                'tingkatan_id' => 2,
                'penghargaan_judul' => 'Juara 1 Frontend Web Design',
                'penghargaan_tempat' => 'Jakarta',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2024-09-01',
                'penghargaan_tanggal_selesai' => '2024-09-05',
                'penghargaan_jumlah_peserta' => 120,
                'penghargaan_jumlah_instansi' => 15,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2024-08-25',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 2250,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 15,
                'lomba_id' => 2,
                'peringkat_id' => 2,
                'tingkatan_id' => 3,
                'penghargaan_judul' => 'Juara 2 Backend API Development',
                'penghargaan_tempat' => 'Surabaya',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2025-04-10',
                'penghargaan_tanggal_selesai' => '2025-04-15',
                'penghargaan_jumlah_peserta' => 80,
                'penghargaan_jumlah_instansi' => 10,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2025-04-01',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 1250,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 9,
                'lomba_id' => 3,
                'peringkat_id' => 3,
                'tingkatan_id' => 2,
                'penghargaan_judul' => 'Juara 3 Indie Game Jam',
                'penghargaan_tempat' => 'Bandung',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2025-07-01',
                'penghargaan_tanggal_selesai' => '2025-07-10',
                'penghargaan_jumlah_peserta' => 60,
                'penghargaan_jumlah_instansi' => 8,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2025-06-25',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 1500,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 1,
                'lomba_id' => 4,
                'peringkat_id' => 4,
                'tingkatan_id' => 1,
                'penghargaan_judul' => 'Harapan 1 React Developer',
                'penghargaan_tempat' => 'Malang',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2024-10-17',
                'penghargaan_tanggal_selesai' => '2024-10-22',
                'penghargaan_jumlah_peserta' => 100,
                'penghargaan_jumlah_instansi' => 12,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2024-10-10',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 2000,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 1,
                'lomba_id' => 5,
                'peringkat_id' => 5,
                'tingkatan_id' => 5,
                'penghargaan_judul' => 'Harapan 2 Android Developer',
                'penghargaan_tempat' => 'Bandung',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2024-10-03',
                'penghargaan_tanggal_selesai' => '2024-10-13',
                'penghargaan_jumlah_peserta' => 90,
                'penghargaan_jumlah_instansi' => 9,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2024-09-28',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 125,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 13,
                'lomba_id' => 6,
                'peringkat_id' => 6,
                'tingkatan_id' => 1,
                'penghargaan_judul' => 'Harapan 3 UI/UX Designer',
                'penghargaan_tempat' => 'Surabaya',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2024-11-28',
                'penghargaan_tanggal_selesai' => '2024-12-07',
                'penghargaan_jumlah_peserta' => 70,
                'penghargaan_jumlah_instansi' => 7,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2024-11-20',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 1000,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 3,
                'lomba_id' => 7,
                'peringkat_id' => 1,
                'tingkatan_id' => 2,
                'penghargaan_judul' => 'Juara 1 Graphic Designer',
                'penghargaan_tempat' => 'Jakarta',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2024-10-15',
                'penghargaan_tanggal_selesai' => '2024-10-18',
                'penghargaan_jumlah_peserta' => 110,
                'penghargaan_jumlah_instansi' => 10,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2024-10-10',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 2250,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 3,
                'lomba_id' => 8,
                'peringkat_id' => 2,
                'tingkatan_id' => 3,
                'penghargaan_judul' => 'Juara 2 Data Scientist',
                'penghargaan_tempat' => 'Malang',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2025-01-11',
                'penghargaan_tanggal_selesai' => '2025-01-16',
                'penghargaan_jumlah_peserta' => 95,
                'penghargaan_jumlah_instansi' => 8,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2025-01-05',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 1250,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 10,
                'lomba_id' => 9,
                'peringkat_id' => 3,
                'tingkatan_id' => 4,
                'penghargaan_judul' => 'Juara 3 Java Developer',
                'penghargaan_tempat' => 'Bandung',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2024-11-03',
                'penghargaan_tanggal_selesai' => '2024-11-13',
                'penghargaan_jumlah_peserta' => 85,
                'penghargaan_jumlah_instansi' => 7,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2024-10-28',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 500,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 6,
                'lomba_id' => 10,
                'peringkat_id' => 4,
                'tingkatan_id' => 5,
                'penghargaan_judul' => 'Harapan 1 Python Developer',
                'penghargaan_tempat' => 'Surabaya',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2025-03-12',
                'penghargaan_tanggal_selesai' => '2025-03-15',
                'penghargaan_jumlah_peserta' => 75,
                'penghargaan_jumlah_instansi' => 6,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2025-03-01',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 150,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 4,
                'lomba_id' => 11,
                'peringkat_id' => 5,
                'tingkatan_id' => 2,
                'penghargaan_judul' => 'Harapan 2 Cybersecurity Competition',
                'penghargaan_tempat' => 'Jakarta',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2024-08-30',
                'penghargaan_tanggal_selesai' => '2024-09-03',
                'penghargaan_jumlah_peserta' => 130,
                'penghargaan_jumlah_instansi' => 14,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2024-08-20',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 938,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 3,
                'lomba_id' => 12,
                'peringkat_id' => 6,
                'tingkatan_id' => 3,
                'penghargaan_judul' => 'Harapan 3 MySQL Developer',
                'penghargaan_tempat' => 'Malang',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2024-09-26',
                'penghargaan_tanggal_selesai' => '2024-10-03',
                'penghargaan_jumlah_peserta' => 60,
                'penghargaan_jumlah_instansi' => 5,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2024-09-20',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 500,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 4,
                'lomba_id' => 13,
                'peringkat_id' => 1,
                'tingkatan_id' => 1,
                'penghargaan_judul' => 'Juara 1 IoT Developer',
                'penghargaan_tempat' => 'Jakarta',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2024-08-01',
                'penghargaan_tanggal_selesai' => '2024-08-07',
                'penghargaan_jumlah_peserta' => 50,
                'penghargaan_jumlah_instansi' => 4,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2024-07-25',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 3000,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 12,
                'lomba_id' => 14,
                'peringkat_id' => 2,
                'tingkatan_id' => 2,
                'penghargaan_judul' => 'Juara 2 AI Innovation Challenge',
                'penghargaan_tempat' => 'Surabaya',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2024-09-10',
                'penghargaan_tanggal_selesai' => '2024-09-15',
                'penghargaan_jumlah_peserta' => 70,
                'penghargaan_jumlah_instansi' => 6,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2024-09-01',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 1875,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 3,
                'lomba_id' => 15,
                'peringkat_id' => 3,
                'tingkatan_id' => 3,
                'penghargaan_judul' => 'Juara 3 Database Design Contest',
                'penghargaan_tempat' => 'Malang',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2024-10-20',
                'penghargaan_tanggal_selesai' => '2024-10-25',
                'penghargaan_jumlah_peserta' => 65,
                'penghargaan_jumlah_instansi' => 5,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2024-10-10',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 1000,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 14,
                'lomba_id' => 16,
                'peringkat_id' => 4,
                'tingkatan_id' => 4,
                'penghargaan_judul' => 'Harapan 1 Frontend Developer Fest',
                'penghargaan_tempat' => 'Bandung',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2025-01-05',
                'penghargaan_tanggal_selesai' => '2025-01-10',
                'penghargaan_jumlah_peserta' => 80,
                'penghargaan_jumlah_instansi' => 7,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2024-12-28',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 375,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 2,
                'lomba_id' => 17,
                'peringkat_id' => 5,
                'tingkatan_id' => 5,
                'penghargaan_judul' => 'Harapan 2 Startup Ideathon',
                'penghargaan_tempat' => 'Jakarta',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2024-12-01',
                'penghargaan_tanggal_selesai' => '2024-12-05',
                'penghargaan_jumlah_peserta' => 55,
                'penghargaan_jumlah_instansi' => 4,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2024-11-25',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 125,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 17,
                'lomba_id' => 18,
                'peringkat_id' => 6,
                'tingkatan_id' => 1,
                'penghargaan_judul' => 'Harapan 3 Project Manager',
                'penghargaan_tempat' => 'Surabaya',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2024-11-11',
                'penghargaan_tanggal_selesai' => '2024-11-18',
                'penghargaan_jumlah_peserta' => 60,
                'penghargaan_jumlah_instansi' => 5,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2024-11-01',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 1000,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 4,
                'lomba_id' => 19,
                'peringkat_id' => 1,
                'tingkatan_id' => 2,
                'penghargaan_judul' => 'Juara 1 Cloud Computing Challenge',
                'penghargaan_tempat' => 'Malang',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2024-09-21',
                'penghargaan_tanggal_selesai' => '2024-09-30',
                'penghargaan_jumlah_peserta' => 100,
                'penghargaan_jumlah_instansi' => 8,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2024-09-10',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 2250,
                'penghargaan_visible' => true,
            ],
            [
                'mahasiswa_id' => 5,
                'lomba_id' => 20,
                'peringkat_id' => 2,
                'tingkatan_id' => 3,
                'penghargaan_judul' => 'Juara 2 AI and Robotics Expo',
                'penghargaan_tempat' => 'Jakarta',
                'penghargaan_url' => '',
                'penghargaan_tanggal_mulai' => '2025-02-10',
                'penghargaan_tanggal_selesai' => '2025-02-14',
                'penghargaan_jumlah_peserta' => 90,
                'penghargaan_jumlah_instansi' => 7,
                'penghargaan_no_surat_tugas' => '',
                'penghargaan_tanggal_surat_tugas' => '2025-02-01',
                'penghargaan_file_surat_tugas' => '',
                'penghargaan_file_sertifikat' => '',
                'penghargaan_file_poster' => '',
                'penghargaan_photo_kegiatan' => '',
                'penghargaan_score' => 1250,
                'penghargaan_visible' => true,
            ],
        ]);
    }
}
