<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class VerifikasiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('t_verifikasis')->insert([
            [
                'mahasiswa_id' => 1,
                'penghargaan_id' => 1,
                'dosen_id' => 1,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Valid dan sesuai dokumen',
                'verifikasi_dosen_keterangan' => 'Prestasi bagus',
                'verifikasi_admin_tanggal' => '2024-09-01',
                'verifikasi_dosen_tanggal' => '2024-09-01',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 2,
                'penghargaan_id' => 2,
                'dosen_id' => 2,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Ditolak',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Bukti tidak lengkap',
                'verifikasi_dosen_keterangan' => 'Sudah dibimbing dengan baik',
                'verifikasi_admin_tanggal' => '2024-09-02',
                'verifikasi_dosen_tanggal' => '2024-09-02',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 3,
                'penghargaan_id' => 3,
                'dosen_id' => 3,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Dokumen lengkap',
                'verifikasi_dosen_keterangan' => 'Layak diverifikasi',
                'verifikasi_admin_tanggal' => '2025-04-01',
                'verifikasi_dosen_tanggal' => '2025-04-01',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 4,
                'penghargaan_id' => 4,
                'dosen_id' => 1,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Ditolak',
                'verifikasi_dosen_status' => 'Ditolak',
                'verifikasi_admin_keterangan' => 'Tidak sesuai dengan lomba',
                'verifikasi_dosen_keterangan' => 'Belum lengkap laporan',
                'verifikasi_admin_tanggal' => '2025-04-02',
                'verifikasi_dosen_tanggal' => '2025-04-02',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 5,
                'penghargaan_id' => 5,
                'dosen_id' => 2,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Dokumen valid dan lengkap',
                'verifikasi_dosen_keterangan' => 'Prestasi memuaskan',
                'verifikasi_admin_tanggal' => '2024-10-05',
                'verifikasi_dosen_tanggal' => '2024-10-05',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 1,
                'penghargaan_id' => 6,
                'dosen_id' => 3,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Menunggu',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => null,
                'verifikasi_dosen_keterangan' => 'Sudah sesuai kriteria',
                'verifikasi_admin_tanggal' => null,
                'verifikasi_dosen_tanggal' => '2024-11-30',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 2,
                'penghargaan_id' => 7,
                'dosen_id' => 4,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Sertifikat asli dan valid',
                'verifikasi_dosen_keterangan' => 'Hasil kerja yang baik',
                'verifikasi_admin_tanggal' => '2024-10-16',
                'verifikasi_dosen_tanggal' => '2024-10-16',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 8,
                'penghargaan_id' => 8,
                'dosen_id' => 5,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Ditolak',
                'verifikasi_dosen_status' => 'Menunggu',
                'verifikasi_admin_keterangan' => 'Foto kegiatan tidak jelas',
                'verifikasi_dosen_keterangan' => null,
                'verifikasi_admin_tanggal' => '2025-01-12',
                'verifikasi_dosen_tanggal' => null,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 2,
                'penghargaan_id' => 9,
                'dosen_id' => 6,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Prestasi sangat baik',
                'verifikasi_dosen_keterangan' => 'Layak mendapat pengakuan',
                'verifikasi_admin_tanggal' => '2024-11-05',
                'verifikasi_dosen_tanggal' => '2024-11-05',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 2,
                'penghargaan_id' => 10,
                'dosen_id' => 1,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Menunggu',
                'verifikasi_dosen_status' => 'Ditolak',
                'verifikasi_admin_keterangan' => null,
                'verifikasi_dosen_keterangan' => 'Laporan tidak sesuai format',
                'verifikasi_admin_tanggal' => null,
                'verifikasi_dosen_tanggal' => '2025-03-13',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 2,
                'penghargaan_id' => 11,
                'dosen_id' => 2,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Kompetisi tingkat nasional',
                'verifikasi_dosen_keterangan' => 'Prestasi luar biasa',
                'verifikasi_admin_tanggal' => '2024-09-01',
                'verifikasi_dosen_tanggal' => '2024-09-01',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 11,
                'penghargaan_id' => 12,
                'dosen_id' => 3,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Ditolak',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Surat tugas tidak valid',
                'verifikasi_dosen_keterangan' => 'Sudah dibimbing dengan baik',
                'verifikasi_admin_tanggal' => '2024-09-27',
                'verifikasi_dosen_tanggal' => '2024-09-27',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 4,
                'penghargaan_id' => 13,
                'dosen_id' => 4,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Inovasi teknologi IoT',
                'verifikasi_dosen_keterangan' => 'Proyek sangat inovatif',
                'verifikasi_admin_tanggal' => '2024-08-02',
                'verifikasi_dosen_tanggal' => '2024-08-02',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 12,
                'penghargaan_id' => 14,
                'dosen_id' => 5,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Menunggu',
                'verifikasi_dosen_status' => 'Menunggu',
                'verifikasi_admin_keterangan' => null,
                'verifikasi_dosen_keterangan' => null,
                'verifikasi_admin_tanggal' => null,
                'verifikasi_dosen_tanggal' => null,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 6,
                'penghargaan_id' => 15,
                'dosen_id' => 6,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Database design excellent',
                'verifikasi_dosen_keterangan' => 'Pemahaman konsep baik',
                'verifikasi_admin_tanggal' => '2024-10-21',
                'verifikasi_dosen_tanggal' => '2024-10-21',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 7,
                'penghargaan_id' => 16,
                'dosen_id' => 1,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Ditolak',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Tanggal sertifikat tidak sesuai',
                'verifikasi_dosen_keterangan' => 'Skill frontend sangat baik',
                'verifikasi_admin_tanggal' => '2025-01-06',
                'verifikasi_dosen_tanggal' => '2025-01-06',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 9,
                'penghargaan_id' => 17,
                'dosen_id' => 2,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Ditolak',
                'verifikasi_admin_keterangan' => 'Ide startup inovatif',
                'verifikasi_dosen_keterangan' => 'Perlu perbaikan presentasi',
                'verifikasi_admin_tanggal' => '2024-12-02',
                'verifikasi_dosen_tanggal' => '2024-12-02',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 11,
                'penghargaan_id' => 18,
                'dosen_id' => 3,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Menunggu',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => null,
                'verifikasi_dosen_keterangan' => 'Management skills baik',
                'verifikasi_admin_tanggal' => null,
                'verifikasi_dosen_tanggal' => '2024-11-12',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 5,
                'penghargaan_id' => 19,
                'dosen_id' => 4,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Cloud computing expertise',
                'verifikasi_dosen_keterangan' => 'Implementasi cloud sangat baik',
                'verifikasi_admin_tanggal' => '2024-09-22',
                'verifikasi_dosen_tanggal' => '2024-09-22',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 7,
                'penghargaan_id' => 20,
                'dosen_id' => 5,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Ditolak',
                'verifikasi_dosen_status' => 'Menunggu',
                'verifikasi_admin_keterangan' => 'File sertifikat rusak',
                'verifikasi_dosen_keterangan' => null,
                'verifikasi_admin_tanggal' => '2025-02-11',
                'verifikasi_dosen_tanggal' => null,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 16,
                'penghargaan_id' => 21,
                'dosen_id' => 6,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Frontend design excellent',
                'verifikasi_dosen_keterangan' => 'Kreativitas tinggi',
                'verifikasi_admin_tanggal' => '2024-09-02',
                'verifikasi_dosen_tanggal' => '2024-09-02',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 15,
                'penghargaan_id' => 22,
                'dosen_id' => 1,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Menunggu',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => null,
                'verifikasi_dosen_keterangan' => 'API development solid',
                'verifikasi_admin_tanggal' => null,
                'verifikasi_dosen_tanggal' => '2025-04-11',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 9,
                'penghargaan_id' => 23,
                'dosen_id' => 2,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Ditolak',
                'verifikasi_admin_keterangan' => 'Game mechanics innovative',
                'verifikasi_dosen_keterangan' => 'Code quality perlu diperbaiki',
                'verifikasi_admin_tanggal' => '2025-07-02',
                'verifikasi_dosen_tanggal' => '2025-07-02',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 1,
                'penghargaan_id' => 24,
                'dosen_id' => 3,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Ditolak',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Poster lomba tidak sesuai',
                'verifikasi_dosen_keterangan' => 'React implementation good',
                'verifikasi_admin_tanggal' => '2024-10-18',
                'verifikasi_dosen_tanggal' => '2024-10-18',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 1,
                'penghargaan_id' => 25,
                'dosen_id' => 4,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Android app functionality good',
                'verifikasi_dosen_keterangan' => 'Mobile development skills excellent',
                'verifikasi_admin_tanggal' => '2024-10-04',
                'verifikasi_dosen_tanggal' => '2024-10-04',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 13,
                'penghargaan_id' => 26,
                'dosen_id' => 6,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Graphic design creativity high',
                'verifikasi_dosen_keterangan' => 'Visual communication excellent',
                'verifikasi_admin_tanggal' => '2024-10-16',
                'verifikasi_dosen_tanggal' => '2024-10-16',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 2,
                'penghargaan_id' => 27,
                'dosen_id' => 1,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'UI/UX design excellent',
                'verifikasi_dosen_keterangan' => 'User experience outstanding',
                'verifikasi_admin_tanggal' => '2024-11-20',
                'verifikasi_dosen_tanggal' => '2024-11-20',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 8,
                'penghargaan_id' => 28,
                'dosen_id' => 2,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Menunggu',
                'verifikasi_dosen_status' => 'Menunggu',
                'verifikasi_admin_keterangan' => null,
                'verifikasi_dosen_keterangan' => null,
                'verifikasi_admin_tanggal' => null,
                'verifikasi_dosen_tanggal' => null,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 6,
                'penghargaan_id' => 29,
                'dosen_id' => 3,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Menunggu',
                'verifikasi_dosen_status' => 'Ditolak',
                'verifikasi_admin_keterangan' => null,
                'verifikasi_dosen_keterangan' => 'Python code tidak optimal',
                'verifikasi_admin_tanggal' => null,
                'verifikasi_dosen_tanggal' => '2025-03-13',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 4,
                'penghargaan_id' => 30,
                'dosen_id' => 4,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Cybersecurity knowledge deep',
                'verifikasi_dosen_keterangan' => 'Security analysis excellent',
                'verifikasi_admin_tanggal' => '2024-08-31',
                'verifikasi_dosen_tanggal' => '2024-08-31',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 3,
                'penghargaan_id' => 31,
                'dosen_id' => 5,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Ditolak',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'URL sertifikat tidak valid',
                'verifikasi_dosen_keterangan' => 'MySQL optimization good',
                'verifikasi_admin_tanggal' => '2024-09-27',
                'verifikasi_dosen_tanggal' => '2024-09-27',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 4,
                'penghargaan_id' => 32,
                'dosen_id' => 6,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'IoT project innovative',
                'verifikasi_dosen_keterangan' => 'Hardware integration excellent',
                'verifikasi_admin_tanggal' => '2024-08-02',
                'verifikasi_dosen_tanggal' => '2024-08-02',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 12,
                'penghargaan_id' => 33,
                'dosen_id' => 1,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Menunggu',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => null,
                'verifikasi_dosen_keterangan' => 'AI implementation creative',
                'verifikasi_admin_tanggal' => null,
                'verifikasi_dosen_tanggal' => '2024-09-11',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 3,
                'penghargaan_id' => 34,
                'dosen_id' => 2,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Ditolak',
                'verifikasi_admin_keterangan' => 'Database design comprehensive',
                'verifikasi_dosen_keterangan' => 'Query performance perlu diperbaiki',
                'verifikasi_admin_tanggal' => '2024-10-21',
                'verifikasi_dosen_tanggal' => '2024-10-21',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 14,
                'penghargaan_id' => 35,
                'dosen_id' => 3,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Ditolak',
                'verifikasi_dosen_status' => 'Menunggu',
                'verifikasi_admin_keterangan' => 'Foto kegiatan tidak ada',
                'verifikasi_dosen_keterangan' => null,
                'verifikasi_admin_tanggal' => '2025-01-06',
                'verifikasi_dosen_tanggal' => null,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 2,
                'penghargaan_id' => 36,
                'dosen_id' => 4,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Startup concept brilliant',
                'verifikasi_dosen_keterangan' => 'Business model solid',
                'verifikasi_admin_tanggal' => '2024-12-02',
                'verifikasi_dosen_tanggal' => '2024-12-02',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 17,
                'penghargaan_id' => 37,
                'dosen_id' => 5,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Menunggu',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => null,
                'verifikasi_dosen_keterangan' => 'Project management metodologi baik',
                'verifikasi_admin_tanggal' => null,
                'verifikasi_dosen_tanggal' => '2024-11-12',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 4,
                'penghargaan_id' => 38,
                'dosen_id' => 6,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Cloud infrastructure design good',
                'verifikasi_dosen_keterangan' => 'Scalability consideration excellent',
                'verifikasi_admin_tanggal' => '2024-09-22',
                'verifikasi_dosen_tanggal' => '2024-09-22',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 5,
                'penghargaan_id' => 39,
                'dosen_id' => 1,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Ditolak',
                'verifikasi_dosen_status' => 'Menunggu',
                'verifikasi_admin_keterangan' => 'Sertifikat tidak terbaca jelas',
                'verifikasi_dosen_keterangan' => null,
                'verifikasi_admin_tanggal' => '2025-02-11',
                'verifikasi_dosen_tanggal' => null,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 6,
                'penghargaan_id' => 40,
                'dosen_id' => 2,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Machine learning model accurate',
                'verifikasi_dosen_keterangan' => 'Algorithm optimization excellent',
                'verifikasi_admin_tanggal' => '2024-12-01',
                'verifikasi_dosen_tanggal' => '2024-12-01',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 7,
                'penghargaan_id' => 41,
                'dosen_id' => 3,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Menunggu',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => null,
                'verifikasi_dosen_keterangan' => 'Algorithm optimization excellent',
                'verifikasi_admin_tanggal' => null,
                'verifikasi_dosen_tanggal' => '2025-01-20',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 8,
                'penghargaan_id' => 42,
                'dosen_id' => 4,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Leadership skills demonstrated',
                'verifikasi_dosen_keterangan' => 'Team coordination excellent',
                'verifikasi_admin_tanggal' => '2024-11-05',
                'verifikasi_dosen_tanggal' => '2024-11-05',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 9,
                'penghargaan_id' => 43,
                'dosen_id' => 5,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Ditolak',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Tempat lomba tidak sesuai',
                'verifikasi_dosen_keterangan' => 'Coding skills progressive',
                'verifikasi_admin_tanggal' => '2024-08-10',
                'verifikasi_dosen_tanggal' => '2024-08-10',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 10,
                'penghargaan_id' => 44,
                'dosen_id' => 6,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Menunggu',
                'verifikasi_admin_keterangan' => 'Software engineering approach solid',
                'verifikasi_dosen_keterangan' => null,
                'verifikasi_admin_tanggal' => '2024-10-06',
                'verifikasi_dosen_tanggal' => null,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 11,
                'penghargaan_id' => 45,
                'dosen_id' => 1,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Menunggu',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => null,
                'verifikasi_dosen_keterangan' => 'Mobile app performance good',
                'verifikasi_admin_tanggal' => null,
                'verifikasi_dosen_tanggal' => '2025-06-16',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 12,
                'penghargaan_id' => 46,
                'dosen_id' => 2,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Ditolak',
                'verifikasi_admin_keterangan' => 'Blockchain implementation innovative',
                'verifikasi_dosen_keterangan' => 'Smart contract security issue',
                'verifikasi_admin_tanggal' => '2025-05-11',
                'verifikasi_dosen_tanggal' => '2025-05-11',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 13,
                'penghargaan_id' => 47,
                'dosen_id' => 3,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Ditolak',
                'verifikasi_dosen_status' => 'Menunggu',
                'verifikasi_admin_keterangan' => 'File poster tidak dapat diakses',
                'verifikasi_dosen_keterangan' => null,
                'verifikasi_admin_tanggal' => '2025-05-06',
                'verifikasi_dosen_tanggal' => null,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 14,
                'penghargaan_id' => 49,
                'dosen_id' => 4,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Final project excellent',
                'verifikasi_dosen_keterangan' => 'Implementation outstanding',
                'verifikasi_admin_tanggal' => '2024-12-15',
                'verifikasi_dosen_tanggal' => '2024-12-15',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 15,
                'penghargaan_id' => 50,
                'dosen_id' => 5,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Menunggu',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => null,
                'verifikasi_dosen_keterangan' => 'Research methodology good',
                'verifikasi_admin_tanggal' => null,
                'verifikasi_dosen_tanggal' => '2025-01-10',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 16,
                'penghargaan_id' => 51,
                'dosen_id' => 6,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Menunggu',
                'verifikasi_admin_keterangan' => 'CSS animation creativity high',
                'verifikasi_dosen_keterangan' => null,
                'verifikasi_admin_tanggal' => '2025-11-09',
                'verifikasi_dosen_tanggal' => null,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 17,
                'penghargaan_id' => 52,
                'dosen_id' => 1,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Ditolak',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'API documentation incomplete',
                'verifikasi_dosen_keterangan' => 'Technical implementation solid',
                'verifikasi_admin_tanggal' => '2025-12-04',
                'verifikasi_dosen_tanggal' => '2025-12-04',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 1,
                'penghargaan_id' => 53,
                'dosen_id' => 2,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Digital art concept brilliant',
                'verifikasi_dosen_keterangan' => 'Artistic vision excellent',
                'verifikasi_admin_tanggal' => '2026-01-16',
                'verifikasi_dosen_tanggal' => '2026-01-16',
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
            [
                'mahasiswa_id' => 2,
                'penghargaan_id' => 54,
                'dosen_id' => 3,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Menunggu',
                'verifikasi_dosen_status' => 'Menunggu',
                'verifikasi_admin_keterangan' => null,
                'verifikasi_dosen_keterangan' => null,
                'verifikasi_admin_tanggal' => null,
                'verifikasi_dosen_tanggal' => null,
                'created_at' => Carbon::createFromTimestamp(rand(Carbon::create(2021, 1, 1)->timestamp, Carbon::now()->timestamp)),
            ],
        ]);
    }
}
