<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class VerifikasiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $records = [
            // Verifications for penghargaan_id 1-20 (existing awards)
            [
                'mahasiswa_id' => 1,
                'penghargaan_id' => 1,
                'dosen_id' => 1,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Frontend design sangat kreatif dan sesuai standar lomba',
                'verifikasi_dosen_keterangan' => 'Prestasi membanggakan untuk tingkat nasional',
                'verifikasi_admin_tanggal' => '2024-09-06',
                'verifikasi_dosen_tanggal' => '2024-09-06',
                'created_at' => Carbon::create(2024, 9, 6),
            ],
            [
                'mahasiswa_id' => 2,
                'penghargaan_id' => 2,
                'dosen_id' => 2,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'API documentation lengkap dan implementasi solid',
                'verifikasi_dosen_keterangan' => 'Backend development skills excellent',
                'verifikasi_admin_tanggal' => '2025-04-16',
                'verifikasi_dosen_tanggal' => '2025-04-16',
                'created_at' => Carbon::create(2025, 4, 16),
            ],
            [
                'mahasiswa_id' => 3,
                'penghargaan_id' => 3,
                'dosen_id' => 3,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Game mechanics innovative dan engaging',
                'verifikasi_dosen_keterangan' => 'Creativity dalam game development sangat baik',
                'verifikasi_admin_tanggal' => '2025-07-11',
                'verifikasi_dosen_tanggal' => '2025-07-11',
                'created_at' => Carbon::create(2025, 7, 11),
            ],
            [
                'mahasiswa_id' => 4,
                'penghargaan_id' => 4,
                'dosen_id' => 4,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'React component architecture well structured',
                'verifikasi_dosen_keterangan' => 'Good understanding of modern frontend frameworks',
                'verifikasi_admin_tanggal' => '2024-10-23',
                'verifikasi_dosen_tanggal' => '2024-10-23',
                'created_at' => Carbon::create(2024, 10, 23),
            ],
            [
                'mahasiswa_id' => 5,
                'penghargaan_id' => 5,
                'dosen_id' => 5,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Android app performance optimization baik',
                'verifikasi_dosen_keterangan' => 'Mobile development skills progressif',
                'verifikasi_admin_tanggal' => '2024-10-14',
                'verifikasi_dosen_tanggal' => '2024-10-14',
                'created_at' => Carbon::create(2024, 10, 14),
            ],
            [
                'mahasiswa_id' => 1,
                'penghargaan_id' => 6,
                'dosen_id' => 6,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Menunggu',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => null,
                'verifikasi_dosen_keterangan' => 'UI/UX design principles well applied',
                'verifikasi_admin_tanggal' => null,
                'verifikasi_dosen_tanggal' => '2024-12-08',
                'created_at' => Carbon::create(2024, 12, 8),
            ],
            [
                'mahasiswa_id' => 2,
                'penghargaan_id' => 7,
                'dosen_id' => 1,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Graphic design creativity tingkat tinggi',
                'verifikasi_dosen_keterangan' => 'Visual communication skills excellent',
                'verifikasi_admin_tanggal' => '2024-10-19',
                'verifikasi_dosen_tanggal' => '2024-10-19',
                'created_at' => Carbon::create(2024, 10, 19),
            ],
            [
                'mahasiswa_id' => 8,
                'penghargaan_id' => 8,
                'dosen_id' => 2,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Ditolak',
                'verifikasi_dosen_status' => 'Menunggu',
                'verifikasi_admin_keterangan' => 'Dataset source tidak jelas, perlu dokumentasi lebih detail',
                'verifikasi_dosen_keterangan' => null,
                'verifikasi_admin_tanggal' => '2025-01-17',
                'verifikasi_dosen_tanggal' => null,
                'created_at' => Carbon::create(2025, 1, 17),
            ],
            [
                'mahasiswa_id' => 2,
                'penghargaan_id' => 9,
                'dosen_id' => 3,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Java application architecture solid',
                'verifikasi_dosen_keterangan' => 'Object-oriented programming skills baik',
                'verifikasi_admin_tanggal' => '2024-11-14',
                'verifikasi_dosen_tanggal' => '2024-11-14',
                'created_at' => Carbon::create(2024, 11, 14),
            ],
            [
                'mahasiswa_id' => 2,
                'penghargaan_id' => 10,
                'dosen_id' => 4,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Menunggu',
                'verifikasi_dosen_status' => 'Ditolak',
                'verifikasi_admin_keterangan' => null,
                'verifikasi_dosen_keterangan' => 'Code structure perlu improvement, dokumentasi kurang',
                'verifikasi_admin_tanggal' => null,
                'verifikasi_dosen_tanggal' => '2025-03-16',
                'created_at' => Carbon::create(2025, 3, 16),
            ],
            [
                'mahasiswa_id' => 2,
                'penghargaan_id' => 11,
                'dosen_id' => 5,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Cybersecurity knowledge comprehensive',
                'verifikasi_dosen_keterangan' => 'Security analysis methodology excellent',
                'verifikasi_admin_tanggal' => '2024-09-04',
                'verifikasi_dosen_tanggal' => '2024-09-04',
                'created_at' => Carbon::create(2024, 9, 4),
            ],
            [
                'mahasiswa_id' => 11,
                'penghargaan_id' => 12,
                'dosen_id' => 6,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Ditolak',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Sertifikat tidak memiliki verifikasi QR code',
                'verifikasi_dosen_keterangan' => 'Database optimization techniques good',
                'verifikasi_admin_tanggal' => '2024-10-04',
                'verifikasi_dosen_tanggal' => '2024-10-04',
                'created_at' => Carbon::create(2024, 10, 4),
            ],
            [
                'mahasiswa_id' => 4,
                'penghargaan_id' => 13,
                'dosen_id' => 1,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'IoT prototype sangat inovatif dan applicable',
                'verifikasi_dosen_keterangan' => 'Hardware-software integration excellent',
                'verifikasi_admin_tanggal' => '2024-08-08',
                'verifikasi_dosen_tanggal' => '2024-08-08',
                'created_at' => Carbon::create(2024, 8, 8),
            ],
            [
                'mahasiswa_id' => 12,
                'penghargaan_id' => 14,
                'dosen_id' => 2,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Menunggu',
                'verifikasi_dosen_status' => 'Menunggu',
                'verifikasi_admin_keterangan' => null,
                'verifikasi_dosen_keterangan' => null,
                'verifikasi_admin_tanggal' => null,
                'verifikasi_dosen_tanggal' => null,
                'created_at' => Carbon::create(2024, 9, 16),
            ],
            [
                'mahasiswa_id' => 6,
                'penghargaan_id' => 15,
                'dosen_id' => 3,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Database normalization dan indexing strategies baik',
                'verifikasi_dosen_keterangan' => 'ERD design comprehensive dan well-structured',
                'verifikasi_admin_tanggal' => '2024-10-26',
                'verifikasi_dosen_tanggal' => '2024-10-26',
                'created_at' => Carbon::create(2024, 10, 26),
            ],
            [
                'mahasiswa_id' => 7,
                'penghargaan_id' => 16,
                'dosen_id' => 4,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Ditolak',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'File portfolio tidak dapat diakses dari link yang diberikan',
                'verifikasi_dosen_keterangan' => 'Frontend skills dan responsive design good',
                'verifikasi_admin_tanggal' => '2025-01-11',
                'verifikasi_dosen_tanggal' => '2025-01-11',
                'created_at' => Carbon::create(2025, 1, 11),
            ],
            [
                'mahasiswa_id' => 9,
                'penghargaan_id' => 17,
                'dosen_id' => 5,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Ditolak',
                'verifikasi_admin_keterangan' => 'Business model dan pitch presentation convincing',
                'verifikasi_dosen_keterangan' => 'Technical implementation belum mature',
                'verifikasi_admin_tanggal' => '2024-12-06',
                'verifikasi_dosen_tanggal' => '2024-12-06',
                'created_at' => Carbon::create(2024, 12, 6),
            ],
            [
                'mahasiswa_id' => 11,
                'penghargaan_id' => 18,
                'dosen_id' => 6,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Menunggu',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => null,
                'verifikasi_dosen_keterangan' => 'Project management methodology dan execution baik',
                'verifikasi_admin_tanggal' => null,
                'verifikasi_dosen_tanggal' => '2024-11-19',
                'created_at' => Carbon::create(2024, 11, 19),
            ],
            [
                'mahasiswa_id' => 5,
                'penghargaan_id' => 19,
                'dosen_id' => 1,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Cloud architecture design dan scalability excellent',
                'verifikasi_dosen_keterangan' => 'Cloud computing concepts well implemented',
                'verifikasi_admin_tanggal' => '2024-10-01',
                'verifikasi_dosen_tanggal' => '2024-10-01',
                'created_at' => Carbon::create(2024, 10, 1),
            ],
            [
                'mahasiswa_id' => 7,
                'penghargaan_id' => 20,
                'dosen_id' => 2,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Ditolak',
                'verifikasi_dosen_status' => 'Menunggu',
                'verifikasi_admin_keterangan' => 'Video demo robot tidak menunjukkan fungsi AI dengan jelas',
                'verifikasi_dosen_keterangan' => null,
                'verifikasi_admin_tanggal' => '2025-02-15',
                'verifikasi_dosen_tanggal' => null,
                'created_at' => Carbon::create(2025, 2, 15),
            ],

            // Verifications for penghargaan_id 21-40 (new awards)
            [
                'mahasiswa_id' => 13,
                'penghargaan_id' => 21,
                'dosen_id' => 3,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Blockchain implementation sangat innovative di tingkat internasional',
                'verifikasi_dosen_keterangan' => 'Smart contract development skills outstanding',
                'verifikasi_admin_tanggal' => '2024-08-21',
                'verifikasi_dosen_tanggal' => '2024-08-21',
                'created_at' => Carbon::create(2024, 8, 21),
            ],
            [
                'mahasiswa_id' => 14,
                'penghargaan_id' => 22,
                'dosen_id' => 4,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Machine learning model accuracy dan implementation excellent',
                'verifikasi_dosen_keterangan' => 'Data preprocessing dan feature engineering sangat baik',
                'verifikasi_admin_tanggal' => '2024-09-11',
                'verifikasi_dosen_tanggal' => '2024-09-11',
                'created_at' => Carbon::create(2024, 9, 11),
            ],
            [
                'mahasiswa_id' => 15,
                'penghargaan_id' => 23,
                'dosen_id' => 5,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Cybersecurity solution comprehensive dan applicable',
                'verifikasi_dosen_keterangan' => 'Penetration testing methodology sangat baik',
                'verifikasi_admin_tanggal' => '2024-10-06',
                'verifikasi_dosen_tanggal' => '2024-10-06',
                'created_at' => Carbon::create(2024, 10, 6),
            ],
            [
                'mahasiswa_id' => 16,
                'penghargaan_id' => 24,
                'dosen_id' => 6,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Web development dengan modern framework sangat baik',
                'verifikasi_dosen_keterangan' => 'Full-stack development skills comprehensive',
                'verifikasi_admin_tanggal' => '2024-11-16',
                'verifikasi_dosen_tanggal' => '2024-11-16',
                'created_at' => Carbon::create(2024, 11, 16),
            ],
            [
                'mahasiswa_id' => 17,
                'penghargaan_id' => 25,
                'dosen_id' => 1,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Menunggu',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => null,
                'verifikasi_dosen_keterangan' => 'Mobile app development skills good progress',
                'verifikasi_admin_tanggal' => null,
                'verifikasi_dosen_tanggal' => '2024-12-04',
                'created_at' => Carbon::create(2024, 12, 4),
            ],
            [
                'mahasiswa_id' => 18,
                'penghargaan_id' => 26,
                'dosen_id' => 2,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'AI innovation di level internasional sangat membanggakan',
                'verifikasi_dosen_keterangan' => 'Research methodology dan implementation outstanding',
                'verifikasi_admin_tanggal' => '2025-03-26',
                'verifikasi_dosen_tanggal' => '2025-03-26',
                'created_at' => Carbon::create(2025, 3, 26),
            ],
            [
                'mahasiswa_id' => 19,
                'penghargaan_id' => 27,
                'dosen_id' => 3,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Data analytics approach dan visualization excellent',
                'verifikasi_dosen_keterangan' => 'Statistical analysis dan insights generation baik',
                'verifikasi_admin_tanggal' => '2024-07-21',
                'verifikasi_dosen_tanggal' => '2024-07-21',
                'created_at' => Carbon::create(2024, 7, 21),
            ],
            [
                'mahasiswa_id' => 20,
                'penghargaan_id' => 28,
                'dosen_id' => 4,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Menunggu',
                'verifikasi_dosen_status' => 'Menunggu',
                'verifikasi_admin_keterangan' => null,
                'verifikasi_dosen_keterangan' => null,
                'verifikasi_admin_tanggal' => null,
                'verifikasi_dosen_tanggal' => null,
                'created_at' => Carbon::create(2024, 6, 16),
            ],
            [
                'mahasiswa_id' => 21,
                'penghargaan_id' => 29,
                'dosen_id' => 5,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Ditolak',
                'verifikasi_admin_keterangan' => 'IoT prototype functional dan innovative',
                'verifikasi_dosen_keterangan' => 'Documentation kurang detail, perlu improvement',
                'verifikasi_admin_tanggal' => '2024-05-26',
                'verifikasi_dosen_tanggal' => '2024-05-26',
                'created_at' => Carbon::create(2024, 5, 26),
            ],
            [
                'mahasiswa_id' => 22,
                'penghargaan_id' => 30,
                'dosen_id' => 6,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Programming logic dan algorithm implementation good',
                'verifikasi_dosen_keterangan' => 'Problem-solving approach systematic',
                'verifikasi_admin_tanggal' => '2024-04-18',
                'verifikasi_dosen_tanggal' => '2024-04-18',
                'created_at' => Carbon::create(2024, 4, 18),
            ],
            [
                'mahasiswa_id' => 23,
                'penghargaan_id' => 31,
                'dosen_id' => 1,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Software engineering practices di tingkat internasional impressive',
                'verifikasi_dosen_keterangan' => 'System design dan architecture thinking excellent',
                'verifikasi_admin_tanggal' => '2025-05-16',
                'verifikasi_dosen_tanggal' => '2025-05-16',
                'created_at' => Carbon::create(2025, 5, 16),
            ],
            [
                'mahasiswa_id' => 24,
                'penghargaan_id' => 32,
                'dosen_id' => 2,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Ditolak',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Portfolio link tidak dapat diakses',
                'verifikasi_dosen_keterangan' => 'Database design principles well understood',
                'verifikasi_admin_tanggal' => '2024-08-31',
                'verifikasi_dosen_tanggal' => '2024-08-31',
                'created_at' => Carbon::create(2024, 8, 31),
            ],
            [
                'mahasiswa_id' => 25,
                'penghargaan_id' => 33,
                'dosen_id' => 3,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Menunggu',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => null,
                'verifikasi_dosen_keterangan' => 'Game development creativity dan technical skills good',
                'verifikasi_admin_tanggal' => null,
                'verifikasi_dosen_tanggal' => '2024-09-21',
                'created_at' => Carbon::create(2024, 9, 21),
            ],
            [
                'mahasiswa_id' => 26,
                'penghargaan_id' => 34,
                'dosen_id' => 4,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'UX research dan UI design process well documented',
                'verifikasi_dosen_keterangan' => 'User-centered design approach excellent',
                'verifikasi_admin_tanggal' => '2024-10-09',
                'verifikasi_dosen_tanggal' => '2024-10-09',
                'created_at' => Carbon::create(2024, 10, 9),
            ],
            [
                'mahasiswa_id' => 27,
                'penghargaan_id' => 35,
                'dosen_id' => 5,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Web design creativity dan responsiveness good',
                'verifikasi_dosen_keterangan' => 'Frontend development fundamentals solid',
                'verifikasi_admin_tanggal' => '2023-11-23',
                'verifikasi_dosen_tanggal' => '2023-11-23',
                'created_at' => Carbon::create(2023, 11, 23),
            ],
            [
                'mahasiswa_id' => 28,
                'penghargaan_id' => 36,
                'dosen_id' => 6,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Robotics engineering di tingkat internasional outstanding',
                'verifikasi_dosen_keterangan' => 'Mechanical dan programming integration excellent',
                'verifikasi_admin_tanggal' => '2022-06-07',
                'verifikasi_dosen_tanggal' => '2022-06-07',
                'created_at' => Carbon::create(2022, 6, 7),
            ],
            [
                'mahasiswa_id' => 29,
                'penghargaan_id' => 37,
                'dosen_id' => 1,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Menunggu',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => null,
                'verifikasi_dosen_keterangan' => 'Cloud computing architecture dan implementation good',
                'verifikasi_admin_tanggal' => null,
                'verifikasi_dosen_tanggal' => '2024-12-16',
                'created_at' => Carbon::create(2024, 12, 16),
            ],
            [
                'mahasiswa_id' => 30,
                'penghargaan_id' => 38,
                'dosen_id' => 2,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Software testing methodology comprehensive',
                'verifikasi_dosen_keterangan' => 'Quality assurance processes well implemented',
                'verifikasi_admin_tanggal' => '2025-01-26',
                'verifikasi_dosen_tanggal' => '2025-01-26',
                'created_at' => Carbon::create(2025, 1, 26),
            ],
            [
                'mahasiswa_id' => 31,
                'penghargaan_id' => 39,
                'dosen_id' => 3,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Ditolak',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'Demo video e-commerce tidak menunjukkan semua fitur',
                'verifikasi_dosen_keterangan' => 'E-commerce development skills good',
                'verifikasi_admin_tanggal' => '2024-07-13',
                'verifikasi_dosen_tanggal' => '2024-07-13',
                'created_at' => Carbon::create(2024, 7, 13),
            ],
            [
                'mahasiswa_id' => 32,
                'penghargaan_id' => 40,
                'dosen_id' => 4,
                'admin_id' => 1,
                'verifikasi_admin_status' => 'Diterima',
                'verifikasi_dosen_status' => 'Diterima',
                'verifikasi_admin_keterangan' => 'IT innovation presentation engaging dan applicable',
                'verifikasi_dosen_keterangan' => 'Technology solution creative dan practical',
                'verifikasi_admin_tanggal' => '2024-06-28',
                'verifikasi_dosen_tanggal' => '2024-06-28',
                'created_at' => Carbon::create(2024, 6, 28),
            ],
        ];

        // Process each record to add verifikasi_verified_at
        foreach ($records as &$record) {
            if ($record['verifikasi_admin_status'] === 'Diterima' && $record['verifikasi_dosen_status'] === 'Diterima') {
                // Set verified_at to the later of the two verification dates
                $adminDate = $record['verifikasi_admin_tanggal'] ? Carbon::parse($record['verifikasi_admin_tanggal']) : null;
                $dosenDate = $record['verifikasi_dosen_tanggal'] ? Carbon::parse($record['verifikasi_dosen_tanggal']) : null;
                
                if ($adminDate && $dosenDate) {
                    $record['verifikasi_verified_at'] = $adminDate->greaterThan($dosenDate) ? $adminDate : $dosenDate;
                } else {
                    $record['verifikasi_verified_at'] = null;
                }
            } else {
                $record['verifikasi_verified_at'] = null;
            }
        }

        DB::table('t_verifikasis')->insert($records);
    }
}